# -*- coding: utf-8 -*-
"""01_eda_and_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oYQzbZv6ddhgTAzAiKyoH5hfV8yNpqC3

# Credit Default Risk Prediction

## Tunahan — EDA, Data Cleaning & Business Interpretation

### Day 1 — Data Loading & Target Distribution

Bu bölümde:
- Proje çalışma ortamı hazırlanacaktır.
- Ham UCI Credit Card verisi yüklenecektir.
- Veri setinin temel yapısı kontrol edilecektir.
- Hedef değişkenin dağılımı incelenecektir.
- Sınıf dengesizliğinin modelleme açısından etkisi yorumlanacaktır.
"""

from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path

drive_root = Path("/content/drive/MyDrive")

matches = list(drive_root.rglob("UCI_Credit_Card.csv"))

matches

!find -L /content/drive -iname "UCI_Credit_Card.csv" 2>/dev/null

# Ham veri setinin Google Drive üzerindeki dosya yolunu tanımlıyoruz.
# raw klasöründeki dosyayı değiştirmeyeceğiz; sadece okuyacağız.
DATA_PATH = "/content/drive/MyDrive/Credit_Card_Analysis_Project/data/raw/UCI_Credit_Card.csv"

import os

os.path.exists(DATA_PATH)

# Gerekli kütüphaneleri içe aktarıyoruz.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# DataFrame içindeki tüm kolonları görebilmek için pandas görüntüleme ayarını değiştiriyoruz.
pd.set_option("display.max_columns", None)

# CSV formatındaki ham veri setini pandas DataFrame olarak yüklüyoruz.
df = pd.read_csv(DATA_PATH)

# Veri setinin ilk 5 satırını görüntülüyoruz.
# Bu sayede kolon isimlerinin ve verilerin doğru yüklenip yüklenmediğini hızlıca kontrol ediyoruz.
df.head()

# Veri setinin satır ve kolon sayısını kontrol ediyoruz.
# Çıktı: (satır sayısı, kolon sayısı)
df.shape

# Veri setindeki tüm kolon isimlerini liste halinde görüntülüyoruz.
# Hedef değişkenin ve beklediğimiz finansal/demografik değişkenlerin mevcut olup olmadığını kontrol edeceğiz.
df.columns.tolist()

# Kolonların veri tiplerini ve eksik değer durumlarını genel olarak inceliyoruz.
# Bu aşama veri setinin yapısını anlamak için kullanılıyor; henüz herhangi bir temizleme işlemi yapmıyoruz.
df.info()

# Her kolondaki eksik (NaN) değer sayısını kontrol ediyoruz.
# df.info() sonucunda eksik değer görünmedi ancak bunu
# programatik olarak da doğrulamak istiyoruz.
df.isnull().sum()

# Veri setinin tamamındaki toplam eksik değer sayısını hesaplıyoruz.
# Sonuç 0 ise dataset içerisinde pandas tarafından eksik
# olarak algılanan herhangi bir değer bulunmuyor demektir.
df.isnull().sum().sum()

"""# Eksik değer kontrolü sonucunda veri setinde herhangi bir missing value bulunmadı.
# Bu nedenle şu aşamada eksik değer doldurma veya satır silme işlemi gerekmiyor.
"""

# Veri setinde tamamen aynı olan tekrar satırlar var mı kontrol ediyoruz.
# Duplicate gözlemler modelleme sonuçlarını ve istatistikleri bozabileceği için
# veri temizliği öncesinde bu kontrolü yapıyoruz.
df.duplicated().sum()

# ID değişkeninin her müşteri/kayıt için benzersiz olup olmadığını kontrol ediyoruz.
# Aynı ID'nin birden fazla satırda bulunması veri kalitesi problemi olabilir.
df["ID"].duplicated().sum()

# Hedef değişkende hangi farklı değerlerin bulunduğunu kontrol ediyoruz.
# Binary classification problemi olduğu için burada yalnızca 0 ve 1
# değerlerini görmeyi bekliyoruz.
df["default.payment.next.month"].unique()

# Hedef değişkendeki her sınıfın kaç müşteriden oluştuğunu inceliyoruz.
# Bu çıktı bize default olan ve olmayan müşteri sayılarını gösterecek.
df["default.payment.next.month"].value_counts()

# Hedef değişkendeki sınıfların yüzde dağılımını hesaplıyoruz.
# normalize=True, müşteri sayılarını toplam gözlem sayısına oranlar.
# 100 ile çarparak sonucu yüzde formatına dönüştürüyoruz.
target_percentages = (
    df["default.payment.next.month"]
    .value_counts(normalize=True)
    .sort_index()
    * 100
)

# Sonuçları iki ondalık basamakla görüntülüyoruz.
target_percentages.round(2)

# Default olmayan müşteri sayısını alıyoruz.
non_default_count = df["default.payment.next.month"].value_counts()[0]

# Default olan müşteri sayısını alıyoruz.
default_count = df["default.payment.next.month"].value_counts()[1]

# Sınıflar arasındaki sayısal oranı hesaplıyoruz.
# Bu oran, kaç default olmayan müşteriye karşılık
# yaklaşık 1 default müşterisi bulunduğunu gösterir.
imbalance_ratio = non_default_count / default_count

# Sonucu iki ondalık basamakla görüntülüyoruz.
round(imbalance_ratio, 2)

"""### Hedef Değişken Yorumu

Hedef değişkenin dağılımı belirgin bir sınıf dengesizliği göstermektedir.

- Müşterilerin %77.88'i takip eden ay default durumuna düşmemiştir.
- Müşterilerin %22.12'si takip eden ay default durumuna düşmüştür.

Bu dağılım yaklaşık 3.5:1 sınıf oranına karşılık gelmektedir.

Bu nedenle model performansını değerlendirirken yalnızca accuracy metriğini kullanmak yanıltıcı olabilir.

Kredi riski açısından özellikle gerçekten default durumuna düşecek müşterilerin doğru tespit edilmesi önemlidir. Bu nedenle Recall, Precision, F1-score, ROC-AUC ve PR-AUC gibi metriklerin de birlikte değerlendirilmesi gerekmektedir.
"""

# Hedef değişkendeki sınıf sayılarını sıralı şekilde alıyoruz.
# 0 = Default olmayan müşteri
# 1 = Default olan müşteri
target_counts = (
    df["default.payment.next.month"]
    .value_counts()
    .sort_index()
)

# Default dağılımını bar chart ile görselleştiriyoruz.
# Bu grafik sınıf dengesizliğini görsel olarak daha net göstermemizi sağlar.
target_counts.plot(
    kind="bar",
    figsize=(7, 5)
)

# Grafiğin başlığını ve eksen isimlerini belirliyoruz.
plt.title("Distribution of Credit Default")
plt.xlabel("Default Status")
plt.ylabel("Number of Customers")

# 0 ve 1 değerlerini daha anlaşılır etiketlerle gösteriyoruz.
plt.xticks(
    ticks=[0, 1],
    labels=["No Default (0)", "Default (1)"],
    rotation=0
)

# Grafikteki öğelerin düzgün yerleşmesini sağlıyoruz.
plt.tight_layout()

# Grafiği ekranda gösteriyoruz.
plt.show()

"""### Hedef Değişken Yorumu

Hedef değişkenin dağılımı belirgin bir sınıf dengesizliği göstermektedir.

- Müşterilerin %77.88'i takip eden ay default durumuna düşmemiştir.
- Müşterilerin %22.12'si takip eden ay default durumuna düşmüştür.
- Bu dağılım yaklaşık 3.52:1 sınıf oranına karşılık gelmektedir.

Bu nedenle model performansını değerlendirirken yalnızca accuracy metriğini kullanmak yanıltıcı olabilir.

Kredi riski açısından özellikle gerçekten default durumuna düşecek müşterilerin doğru tespit edilmesi önemlidir. Bu nedenle Recall, Precision, F1-score, ROC-AUC ve PR-AUC gibi metriklerin de birlikte değerlendirilmesi gerekmektedir.
"""

# Sayısal değişkenlerin temel tanımlayıcı istatistiklerini inceliyoruz.
# Bu tablo; minimum, maksimum, ortalama ve çeyreklik değerleri görmemizi sağlar.
# Şimdilik anomalileri düzeltmiyoruz, yalnızca ileride incelemek üzere gözlemliyoruz.
df.describe().T

"""### İlk Tanımlayıcı İstatistik Gözlemleri

Tanımlayıcı istatistikler incelendiğinde veri setinde ilerleyen aşamalarda
araştırılması gereken bazı noktalar görülmüştür:

- `EDUCATION` değişkeninde 0 ile 6 arasında kategori kodları bulunmaktadır.
- `MARRIAGE` değişkeninde 0 kodu bulunmaktadır.
- `PAY_X` değişkenleri -2 ile 8 arasında değer almaktadır. Bu değerler
  dokümantasyon doğrulanmadan anomali olarak değerlendirilmeyecektir.
- `BILL_AMT` değişkenlerinde negatif değerler bulunmaktadır.
- Fatura ve ödeme tutarlarında yüksek maksimum değerler gözlenmektedir.

Bu değerler bu aşamada değiştirilmemiştir. Veri temizleme kararları,
değişkenlerin veri sözlüğündeki anlamları ve dağılımları incelendikten sonra
verilecektir.

## 2. Exploratory Data Analysis

### 2.1 Demographic Variables

Bu bölümde müşterilerin demografik özellikleri incelenecektir.

Analiz edilecek değişkenler:
- `SEX`
- `EDUCATION`
- `MARRIAGE`
- `AGE`

Kategorik değişkenlerin kodları, veri seti dokümantasyonundaki tanımları doğrulanmadan yeniden kodlanmayacaktır.
"""

# SEX değişkeninde bulunan farklı kategori kodlarını kontrol ediyoruz.
# Bu aşamada kategorilerin anlamlarını henüz değiştirmiyoruz veya yeniden kodlamıyoruz.
df["SEX"].unique()

# Her SEX kategorisinde kaç müşteri bulunduğunu hesaplıyoruz.
# Böylece kategorilerin veri setindeki dağılımını görebileceğiz.
df["SEX"].value_counts().sort_index()

# SEX kategorilerinin toplam müşteri sayısı içerisindeki yüzde dağılımını hesaplıyoruz.
# normalize=True oranları, 100 ile çarpılması ise yüzdeleri verir.
sex_percentages = (
    df["SEX"]
    .value_counts(normalize=True)
    .sort_index()
    * 100
)

sex_percentages.round(2)

# SEX kategorilerine göre default oranını hesaplıyoruz.
# Hedef değişken 0/1 olduğu için grup içindeki ortalama,
# o grubun default oranına karşılık gelir.
sex_default_rate = (
    df.groupby("SEX")["default.payment.next.month"]
    .mean()
    * 100
)

# Sonuçları iki ondalık basamakla görüntülüyoruz.
sex_default_rate.round(2)

"""#### SEX ve Default İlişkisi

Veri setinde erkek müşterilerin default oranı %24.17, kadın müşterilerin default oranı ise %20.78 olarak gözlenmiştir.

Erkek müşterilerin default oranı kadın müşterilere göre yaklaşık 3.39 yüzde puan daha yüksektir.

Bu sonuç `SEX` değişkeni ile default riski arasında bir ilişki olabileceğini göstermektedir. Ancak bu fark tek başına nedensel bir ilişki olarak yorumlanmamalıdır; kredi limiti, yaş, eğitim ve geçmiş ödeme davranışları gibi diğer değişkenlerin etkileri de dikkate alınmalıdır.
"""

# SEX kategorilerine göre hesapladığımız default oranlarını
# bar chart ile görselleştiriyoruz.
sex_default_rate.plot(
    kind="bar",
    figsize=(7, 5)
)

# Grafiğin başlık ve eksen isimlerini belirliyoruz.
plt.title("Default Rate by Sex")
plt.xlabel("Sex")
plt.ylabel("Default Rate (%)")

# Veri sözlüğündeki kategori kodlarını daha anlaşılır etiketlerle gösteriyoruz.
plt.xticks(
    ticks=[0, 1],
    labels=["Male (1)", "Female (2)"],
    rotation=0
)

# Grafikteki elemanların düzgün yerleşmesini sağlıyoruz.
plt.tight_layout()

# Grafiği ekranda gösteriyoruz.
plt.show()

# EDUCATION değişkeninde veri setinde bulunan farklı kategori kodlarını inceliyoruz.
# Dokümantasyonda 1-4 kodları tanımlı olduğu için özellikle
# 0, 5 ve 6 gibi tanımlanmamış kodların varlığını kontrol ediyoruz.
df["EDUCATION"].unique()

# Her EDUCATION kategorisinde kaç müşteri bulunduğunu hesaplıyoruz.
# Böylece dokümante edilmiş ve edilmemiş kategorilerin büyüklüğünü görebileceğiz.
education_counts = (
    df["EDUCATION"]
    .value_counts()
    .sort_index()
)

education_counts

# EDUCATION kategorilerinin yüzde dağılımını hesaplıyoruz.
# Bu sayede her kategorinin veri setindeki payını görebileceğiz.
education_percentages = (
    df["EDUCATION"]
    .value_counts(normalize=True)
    .sort_index()
    * 100
)

education_percentages.round(2)

"""#### EDUCATION Değişkeni - İlk Gözlem

UCI veri sözlüğünde `EDUCATION` değişkeni için aşağıdaki kategoriler tanımlanmıştır:

- 1 = Graduate school
- 2 = University
- 3 = High school
- 4 = Others

Ancak veri setinde ayrıca 0, 5 ve 6 kodları da bulunmaktadır. Bu kategoriler resmi veri sözlüğünde açıkça tanımlanmamıştır.

Bu nedenle bu değerler şu aşamada değiştirilmemiştir. Veri temizleme aşamasında dağılımları ve iş mantığı dikkate alınarak yeniden değerlendirilecektir.
"""

# EDUCATION kategorilerine göre default oranını hesaplıyoruz.
# Hedef değişken 0/1 olduğu için grup ortalaması,
# ilgili eğitim kategorisindeki default oranını verir.
education_default_rate = (
    df.groupby("EDUCATION")["default.payment.next.month"]
    .mean()
    * 100
)

# Sonuçları kategori koduna göre sıralayıp
# iki ondalık basamakla görüntülüyoruz.
education_default_rate.round(2)

"""#### EDUCATION ve Default İlişkisi

Dokümante edilmiş ana eğitim kategorileri incelendiğinde default oranlarının
eğitim grupları arasında farklılaştığı görülmektedir.

- Graduate school (1): %19.23
- University (2): %23.73
- High school (3): %25.16

Ana gruplar içerisinde graduate school kategorisi en düşük, high school
kategorisi ise en yüksek default oranına sahiptir.

Bununla birlikte 0, 4, 5 ve 6 kategorilerindeki gözlem sayıları ana gruplara
göre oldukça düşüktür. Özellikle dokümantasyonda tanımlanmayan 0, 5 ve 6
kategorilerindeki default oranları küçük örneklem büyüklükleri nedeniyle
temkinli yorumlanmalıdır.

Bu sonuçlar eğitim durumu ile default riski arasında bir ilişki olabileceğini
göstermektedir; ancak tek başına nedensel bir ilişki olarak değerlendirilmemelidir.
"""

# EDUCATION kategorilerine göre hesaplanan default oranlarını
# bar chart ile görselleştiriyoruz.
# Kategori kodlarını şimdilik değiştirmiyoruz çünkü 0, 5 ve 6
# kodlarının anlamı dokümantasyonda açık şekilde tanımlanmamıştır.
education_default_rate.plot(
    kind="bar",
    figsize=(8, 5)
)

# Grafiğin başlık ve eksen isimlerini belirliyoruz.
plt.title("Default Rate by Education")
plt.xlabel("Education Category")
plt.ylabel("Default Rate (%)")

# Kategori kodlarını olduğu gibi gösteriyoruz.
plt.xticks(rotation=0)

# Grafik elemanlarının düzgün yerleşmesini sağlıyoruz.
plt.tight_layout()

# Grafiği ekranda gösteriyoruz.
plt.show()

# MARRIAGE değişkeninde hangi kategori kodlarının bulunduğunu kontrol ediyoruz.
# Dokümantasyonda tanımlanmayan bir kategori varsa bunu veri temizleme
# aşamasında ayrıca değerlendireceğiz.
df["MARRIAGE"].unique()

# Her MARRIAGE kategorisinde kaç müşteri bulunduğunu hesaplıyoruz.
# Böylece kategorilerin veri setindeki dağılımını görebileceğiz.
marriage_counts = (
    df["MARRIAGE"]
    .value_counts()
    .sort_index()
)

marriage_counts

# MARRIAGE kategorilerinin yüzde dağılımını hesaplıyoruz.
# Bu sayede her kategorinin veri setindeki payını görebileceğiz.
marriage_percentages = (
    df["MARRIAGE"]
    .value_counts(normalize=True)
    .sort_index()
    * 100
)

marriage_percentages.round(2)

"""#### MARRIAGE Değişkeni - İlk Gözlem

UCI veri sözlüğünde `MARRIAGE` değişkeni için aşağıdaki kategoriler tanımlanmıştır:

- 1 = Married
- 2 = Single
- 3 = Others

Ancak veri setinde ayrıca 0 kodu da bulunmaktadır. Bu kategori resmi veri sözlüğünde açıkça tanımlanmamıştır.

Bu nedenle 0 kodu şu aşamada değiştirilmemiştir. Veri temizleme aşamasında gözlem sayısı ve iş mantığı dikkate alınarak yeniden değerlendirilecektir.
"""

# MARRIAGE kategorilerine göre default oranını hesaplıyoruz.
# Hedef değişken 0/1 olduğu için grup ortalaması,
# ilgili medeni durum kategorisindeki default oranını verir.
marriage_default_rate = (
    df.groupby("MARRIAGE")["default.payment.next.month"]
    .mean()
    * 100
)

# Sonuçları kategori koduna göre sıralayıp
# iki ondalık basamakla görüntülüyoruz.
marriage_default_rate.round(2)

"""#### MARRIAGE ve Default İlişkisi

Ana medeni durum kategorileri incelendiğinde evli müşterilerin default oranı %23.47,
bekar müşterilerin default oranı ise %20.93 olarak gözlenmiştir.

Evli müşterilerin default oranı bekar müşterilere göre yaklaşık 2.54 yüzde puan daha yüksektir.

`MARRIAGE = 3` kategorisinde default oranı %26.01 ile daha yüksek görünmekle birlikte,
bu grubun gözlem sayısı oldukça düşüktür. Benzer şekilde dokümantasyonda tanımlanmayan
`MARRIAGE = 0` kategorisi yalnızca 54 gözlem içermektedir.

Bu nedenle özellikle küçük kategorilerdeki oranlar temkinli yorumlanmalıdır.
Medeni durum ile default riski arasında bir ilişki gözlenmekle birlikte,
bu sonuç tek başına nedensel bir ilişki olarak değerlendirilmemelidir.
"""

# MARRIAGE kategorilerine göre hesaplanan default oranlarını
# bar chart ile görselleştiriyoruz.
marriage_default_rate.plot(
    kind="bar",
    figsize=(7, 5)
)

# Grafiğin başlık ve eksen isimlerini belirliyoruz.
plt.title("Default Rate by Marital Status")
plt.xlabel("Marital Status")
plt.ylabel("Default Rate (%)")

# Kategori kodlarını daha anlaşılır etiketlerle gösteriyoruz.
# 0 kodu dokümantasyonda tanımlanmadığı için "Undefined" olarak bırakıyoruz.
plt.xticks(
    ticks=[0, 1, 2, 3],
    labels=["Undefined (0)", "Married (1)", "Single (2)", "Others (3)"],
    rotation=0
)

# Grafik elemanlarının düzgün yerleşmesini sağlıyoruz.
plt.tight_layout()

# Grafiği ekranda gösteriyoruz.
plt.show()

# AGE değişkeninin temel istatistiklerini inceliyoruz.
# Böylece minimum, maksimum, ortalama ve çeyreklik yaş değerlerini görebileceğiz.
df["AGE"].describe()

# Müşterilerin yaş dağılımını histogram ile görselleştiriyoruz.
# Histogram, yaşların hangi aralıklarda yoğunlaştığını görmemizi sağlar.
df["AGE"].plot(
    kind="hist",
    bins=20,
    figsize=(8, 5),
    edgecolor="black"
)

# Grafiğin başlık ve eksen isimlerini belirliyoruz.
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Number of Customers")

# Grafik elemanlarının düzgün yerleşmesini sağlıyoruz.
plt.tight_layout()

# Grafiği ekranda gösteriyoruz.
plt.show()

"""#### AGE Değişkeni - İlk Gözlem

Müşterilerin yaş ortalaması 35.49, medyan yaşı ise 34'tür.

Müşterilerin büyük bölümü 20'li yaşların sonu ile 40'lı yaşların başında
yoğunlaşmaktadır. Yaş dağılımı sağa çarpık bir yapı göstermekte ve ileri
yaş gruplarında müşteri sayısı belirgin şekilde azalmaktadır.

Minimum yaş 21, maksimum yaş ise 79'dur. İlk incelemede yaş değişkeninde
iş mantığı açısından açık bir anomali gözlenmemiştir.
"""

# Yaşları 10 yıllık gruplara ayırıyoruz.
# Bu gruplama yalnızca EDA ve görselleştirme amacıyla kullanılacaktır.
# Orijinal AGE değişkenini değiştirmiyoruz.

age_groups = pd.cut(
    df["AGE"],
    bins=[20, 29, 39, 49, 59, 69, 79],
    labels=["21-29", "30-39", "40-49", "50-59", "60-69", "70-79"],
    include_lowest=True
)

# Her yaş grubunda kaç müşteri bulunduğunu hesaplıyoruz.
# Özellikle ileri yaş gruplarında örneklem sayısının küçülüp küçülmediğini
# kontrol etmek için bu bilgi önemli.
age_group_counts = age_groups.value_counts().sort_index()

age_group_counts

# Yaş gruplarına göre default oranını hesaplıyoruz.
# Hedef değişken 0/1 olduğu için grup içerisindeki ortalama,
# o yaş grubundaki default oranına karşılık gelir.
age_default_rate = (
    df.groupby(
        age_groups,
        observed=False
    )["default.payment.next.month"]
    .mean()
    * 100
)

# Default oranlarını iki ondalık basamakla görüntülüyoruz.
age_default_rate.round(2)

"""#### AGE ve Default İlişkisi

Yaş gruplarına göre default oranları incelendiğinde gruplar arasında farklılıklar
olduğu görülmektedir.

- 21-29: %22.84
- 30-39: %20.25
- 40-49: %22.97
- 50-59: %24.86
- 60-69: %28.34
- 70-79: %28.00

30-39 yaş grubu en düşük default oranına sahipken, özellikle 50 yaş ve üzerindeki
gruplarda default oranının yükseldiği gözlenmektedir.

Ancak 60-69 ve özellikle 70-79 yaş gruplarındaki müşteri sayısı diğer gruplara göre
oldukça düşüktür. Bu nedenle ileri yaş gruplarındaki oranlar temkinli
yorumlanmalıdır.

Bu bulgu yaş ile default riski arasında bir ilişki olabileceğini göstermektedir,
ancak yaşın tek başına default riskinin nedeni olduğu şeklinde yorumlanmamalıdır.
"""

# Yaş gruplarına göre hesaplanan default oranlarını
# bar chart ile görselleştiriyoruz.
age_default_rate.plot(
    kind="bar",
    figsize=(8, 5)
)

# Grafiğin başlık ve eksen isimlerini belirliyoruz.
plt.title("Default Rate by Age Group")
plt.xlabel("Age Group")
plt.ylabel("Default Rate (%)")

# Yaş grubu etiketlerinin yatay görünmesini sağlıyoruz.
plt.xticks(rotation=0)

# Grafik elemanlarının düzgün yerleşmesini sağlıyoruz.
plt.tight_layout()

# Grafiği ekranda gösteriyoruz.
plt.show()

# Son 6 aya ait ödeme durumu değişkenlerini bir liste halinde tanımlıyoruz.
# Bu değişkenler müşterinin geçmiş ödeme/gecikme davranışını temsil ediyor.
pay_cols = ["PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6"]

# Her PAY_X değişkeninde hangi farklı kategori kodlarının bulunduğunu inceliyoruz.
# Kodların anlamlarını dokümantasyona göre yorumlayacağız;
# bu aşamada herhangi bir değer değiştirmiyoruz.
for col in pay_cols:
    print(f"{col}: {sorted(df[col].unique())}")

"""#### PAY_X Kodlama Notu

UCI veri sözlüğüne göre ödeme durumu değişkenlerinde:

- -1 = Zamanında ödeme
- 1 = 1 aylık ödeme gecikmesi
- 2 = 2 aylık ödeme gecikmesi
- ...
- 8 = 8 aylık ödeme gecikmesi
- 9 = 9 ay ve üzeri ödeme gecikmesi

Ancak kullanılan veri setinde ayrıca `-2` ve `0` kodları da bulunmaktadır.
Bu iki kodun anlamı resmi UCI veri sözlüğünde açık şekilde tanımlanmamıştır.

Bu nedenle `-2` ve `0` değerleri şu aşamada yeniden kodlanmayacak veya
gecikme süresi olarak doğrudan yorumlanmayacaktır. Temizleme ve feature
engineering kararları verilmeden önce bu durum ayrıca değerlendirilecektir.

#### PAY_X İsimlendirme Notu

Veri setinde `PAY_1` isimli bir değişken bulunmamaktadır.

En güncel ödeme durumu `PAY_0` ile temsil edilmektedir ve sonraki geçmiş aylar
`PAY_2` ile `PAY_6` arasında adlandırılmıştır.

Bu durum veri kaybından değil, veri setinin orijinal değişken isimlendirmesinden
kaynaklanmaktadır.
"""

# Her PAY_X değişkeninde ödeme durumu kodlarının kaç kez görüldüğünü hesaplıyoruz.
# Böylece -2, -1, 0 ve gecikme kodlarının veri içerisindeki dağılımını
# ay bazında karşılaştırabileceğiz.

pay_status_counts = pd.DataFrame({
    col: df[col].value_counts().sort_index()
    for col in pay_cols
}).fillna(0).astype(int)

pay_status_counts

"""#### PAY_X Dağılımı - İlk Gözlemler

Son 6 aya ait ödeme durumu değişkenlerinin frekansları incelendiğinde:

- `0` kodunun tüm aylarda en sık görülen değer olduğu,
- `-1` ve `-2` kodlarının da önemli sayıda gözlem içerdiği,
- pozitif gecikme kodları içerisinde `2` kodunun en yaygın olduğu,
- `3` ve üzerindeki gecikme kodlarının daha seyrek görüldüğü gözlenmiştir.

Ayrıca `1` kodu `PAY_0` değişkeninde oldukça sık görülürken geçmiş aylardaki
`PAY_2`-`PAY_6` değişkenlerinde çok az veya hiç görülmemektedir.

Bu aşamada `-2`, `-1`, `0` ve diğer kodlar yeniden kodlanmamıştır.
Özellikle resmi dokümantasyonda açık şekilde açıklanmayan kodlar için
temizleme veya feature engineering kararı verilmeden önce ek değerlendirme yapılacaktır.

Yüzdesel dağılımlar incelendiğinde `0` kodunun tüm aylarda yaklaşık %49-%56
aralığında olduğu ve en yaygın ödeme durumu kodunu oluşturduğu görülmektedir.

`-1` ve `-2` kodları da veri setinde önemli bir paya sahiptir. Pozitif kodlar
arasında ise `2` kodu en yaygın değer olarak öne çıkmaktadır.

Özellikle `PAY_0` değişkenindeki `1` kodunun %12.29 oranında görülmesine karşın
diğer aylarda bu kodun neredeyse hiç bulunmaması dikkat çekmektedir. Bu durum,
kodlama yapısına ilişkin ayrıca incelenmesi gereken bir gözlem olarak not edilmiştir.
"""

# PAY_X kodlarının her ay içerisindeki yüzde dağılımını hesaplıyoruz.
# Her PAY_X kolonunda toplam 30.000 gözlem bulunduğu için,
# bu tablo kodların o ay içerisindeki payını daha kolay yorumlamamızı sağlar.

pay_status_percentages = (
    pay_status_counts
    .div(pay_status_counts.sum(axis=0), axis=1)
    * 100
)

# Sonuçları iki ondalık basamakla görüntülüyoruz.
pay_status_percentages.round(2)

# PAY_0 kategorilerine göre default oranını hesaplıyoruz.
# Hedef değişken 0/1 olduğu için grup ortalaması,
# her PAY_0 kategorisindeki default oranını verir.
#
# Bu aşamada PAY_0 kodlarını yeniden yorumlamıyor veya değiştirmiyoruz;
# yalnızca mevcut kodlarla default arasındaki ilişkiyi gözlemliyoruz.

pay0_default_rate = (
    df.groupby("PAY_0")["default.payment.next.month"]
    .mean()
    * 100
)

# Sonuçları iki ondalık basamakla görüntülüyoruz.
pay0_default_rate.round(2)

"""#### PAY_0 ve Default İlişkisi

En güncel ödeme durumu olan `PAY_0` ile default oranı arasında güçlü bir ilişki
gözlenmektedir.

`PAY_0` değeri 1 olan müşterilerde default oranı %33.95 iken, bu oran
2 kodunda %69.14'e ve 3 kodunda %75.78'e yükselmektedir.

Bu bulgu, yakın dönemde ödeme gecikmesi bulunan müşterilerin gelecek ay
default durumuna düşme olasılığının belirgin şekilde daha yüksek olduğunu
göstermektedir.

Bununla birlikte 4 ve üzerindeki PAY_0 kategorilerinde gözlem sayıları oldukça
düşüktür. Bu nedenle bu kategorilerdeki default oranları daha değişken olabilir
ve temkinli yorumlanmalıdır.

Ayrıca `-2`, `-1` ve `0` kodlarının tamamının anlamı resmi veri
dokümantasyonunda açık biçimde tanımlanmadığından, bu kategoriler için
kesin finansal yorum yapılmamıştır.
"""

# PAY_0 kategorilerine göre hesaplanan default oranlarını
# bar chart ile görselleştiriyoruz.
# Amaç, ödeme durumu kodları ile default riski arasındaki
# ilişkinin görsel olarak incelenmesidir.

pay0_default_rate.plot(
    kind="bar",
    figsize=(8, 5)
)

# Grafiğin başlık ve eksen isimlerini belirliyoruz.
plt.title("Default Rate by PAY_0 Status")
plt.xlabel("PAY_0 Status")
plt.ylabel("Default Rate (%)")

# PAY_0 kodlarını olduğu gibi gösteriyoruz.
plt.xticks(rotation=0)

# Grafik elemanlarının düzgün yerleşmesini sağlıyoruz.
plt.tight_layout()

# Grafiği ekranda gösteriyoruz.
plt.show()

# Her PAY_X değişkeninde, ödeme durumu kodlarına göre default oranını hesaplıyoruz.
# Böylece son 6 aylık ödeme geçmişinde aynı kodun farklı aylarda
# default riskiyle nasıl ilişkili olduğunu karşılaştırabileceğiz.
#
# Bu aşamada kodları yeniden sınıflandırmıyoruz veya temizlemiyoruz.
# Mevcut değerleri olduğu gibi kullanıyoruz.

pay_default_rates = pd.DataFrame({
    col: (
        df.groupby(col)["default.payment.next.month"]
        .mean()
        * 100
    )
    for col in pay_cols
})

# Sonuçları iki ondalık basamakla görüntülüyoruz.
pay_default_rates.round(2)

"""#### PAY_X Değişkenleri ve Default İlişkisi

Son 6 aya ait ödeme durumu değişkenleri birlikte incelendiğinde, pozitif
gecikme kodları ile default oranı arasında belirgin bir ilişki görülmektedir.

Özellikle `2` ve `3` kodlarına sahip müşterilerde default oranları, `-1` ve
`0` kodlarına sahip müşterilere kıyasla tüm aylarda belirgin şekilde daha yüksektir.

Bu durum geçmiş ödeme gecikmelerinin gelecek ay default riski açısından önemli
bir sinyal taşıdığını göstermektedir. En güncel ödeme durumu olan `PAY_0`
değişkeninde de bu ilişki oldukça belirgindir.

Bununla birlikte `4` ve üzerindeki gecikme kodlarının gözlem sayıları oldukça
düşüktür. Bu nedenle bu kategorilerde görülen yüksek veya dalgalı default
oranları küçük örneklem büyüklüğü nedeniyle temkinli yorumlanmalıdır.

Bazı aylarda `1` kodunun hiç bulunmaması veya çok az gözleme sahip olması da
bu kategorideki oranların aylar arasında doğrudan karşılaştırılmasını
zorlaştırmaktadır.
"""

# Her müşteri için son 6 ayda pozitif gecikme kodu bulunan ay sayısını hesaplıyoruz.
# PAY_X > 0 olan değerleri gecikme göstergesi olarak kabul ediyoruz.
#
# Bu değişken yalnızca EDA amacıyla geçici olarak oluşturulmaktadır.
# Ana dataframe'e yeni bir kolon eklemiyoruz ve feature engineering yapmıyoruz.

delay_month_count_eda = (df[pay_cols] > 0).sum(axis=1)

# Müşterilerin kaç ay gecikme yaşadığına göre dağılımını inceliyoruz.
delay_month_distribution = (
    delay_month_count_eda
    .value_counts()
    .sort_index()
)

delay_month_distribution

"""#### Gecikme Yaşanan Ay Sayısı - İlk Gözlem

Müşterilerin son 6 aylık ödeme geçmişleri incelendiğinde, 19.931 müşterinin
hiçbir ayda pozitif gecikme koduna sahip olmadığı görülmektedir.

Buna karşılık bazı müşteriler birden fazla ay boyunca gecikme davranışı
göstermektedir. Özellikle 1.341 müşterinin incelenen 6 ayın tamamında
pozitif gecikme koduna sahip olması, sürekli gecikme davranışı gösteren
bir müşteri grubunun bulunduğuna işaret etmektedir.

Bu aşamada yalnızca ödeme geçmişi dağılımı incelenmiştir. Gecikme yaşanan
ay sayısının default riskiyle ilişkisi ayrıca değerlendirilecektir.
"""

# EDA amacıyla oluşturduğumuz gecikme yaşanan ay sayısını
# hedef değişken ile birlikte geçici bir tabloya alıyoruz.
# Ana dataframe'e yeni bir kolon eklemiyoruz.

delay_default_eda = pd.DataFrame({
    "delay_month_count": delay_month_count_eda,
    "default": df["default.payment.next.month"]
})

# Son 6 ayda gecikme yaşanan ay sayısına göre
# gelecek ay default oranını hesaplıyoruz.
# Target 0/1 olduğu için grup ortalaması default oranını verir.
delay_month_default_rate = (
    delay_default_eda
    .groupby("delay_month_count")["default"]
    .mean()
    * 100
)

# Sonuçları iki ondalık basamakla görüntülüyoruz.
delay_month_default_rate.round(2)

"""#### Gecikme Yaşanan Ay Sayısı ve Default İlişkisi

Son 6 ay içerisinde pozitif gecikme kodu görülen ay sayısı arttıkça,
gelecek ay default oranının da belirgin biçimde yükseldiği görülmektedir.

- 0 ay gecikme: %11.71
- 1 ay gecikme: %29.82
- 2 ay gecikme: %38.76
- 3 ay gecikme: %50.87
- 4 ay gecikme: %57.31
- 5 ay gecikme: %57.38
- 6 ay gecikme: %70.32

Bu sonuç, yalnızca tek bir aydaki ödeme durumunun değil, gecikme davranışının
sürekliliğinin de default riski açısından önemli bir sinyal taşıdığını
göstermektedir.

Ancak bu analiz gözlemseldir ve tek başına nedensellik anlamına gelmez.
Ayrıca oluşturulan gecikme ayı sayısı bu aşamada yalnızca EDA amacıyla
kullanılmıştır; kalıcı feature engineering kararı ayrı aşamada verilecektir.
"""

# Gecikme yaşanan ay sayısına göre default oranını
# bar chart ile görselleştiriyoruz.
# Amaç, tekrarlayan gecikme davranışı ile default riski
# arasındaki ilişkiyi daha net göstermektir.

delay_month_default_rate.plot(
    kind="bar",
    figsize=(8, 5)
)

# Grafiğin başlık ve eksen isimlerini belirliyoruz.
plt.title("Default Rate by Number of Delayed Months")
plt.xlabel("Number of Delayed Months")
plt.ylabel("Default Rate (%)")

# X eksenindeki değerleri yatay gösteriyoruz.
plt.xticks(rotation=0)

# Grafik elemanlarının düzgün yerleşmesini sağlıyoruz.
plt.tight_layout()

# Grafiği ekranda gösteriyoruz.
plt.show()

"""## 3. Data Cleaning and Anomaly Investigation

Bu bölümde EDA sırasında tespit edilen veri kalitesi sorunları incelenecek
ve gerekli temizleme kararları iş mantığı ve veri dokümantasyonu dikkate
alınarak verilecektir.

Ham veri seti korunacak ve tüm temizleme işlemleri çalışma kopyası üzerinde
gerçekleştirilecektir.
"""

# Ham dataframe'i korumak için temizleme işlemlerinde kullanacağımız
# ayrı bir çalışma kopyası oluşturuyoruz.
# Böylece df üzerinde doğrudan değişiklik yapmıyoruz.

df_clean = df.copy()

# Kopyanın doğru oluşturulduğunu kontrol ediyoruz.
df_clean.shape

"""### 3.1 EDUCATION Temizleme Kararı

UCI veri sözlüğünde `EDUCATION` değişkeni için:

- 1 = Graduate school
- 2 = University
- 3 = High school
- 4 = Others

kategorileri tanımlanmaktadır.

Ancak veri setinde ayrıca 0, 5 ve 6 kodları da bulunmaktadır ve bu kodların
resmi dokümantasyonda açık bir karşılığı bulunmamaktadır.

Bu kategoriler toplam veri setinin küçük bir bölümünü oluşturduğu için
gözlemleri silmek yerine `4 = Others` kategorisi altında birleştirilmesine
karar verilmiştir.

Bu işlem veri kaybını önlerken, dokümante edilmemiş kategorilerin ayrı ve
anlamsız sınıflar olarak modellemeye girmesini de engellemektedir.
"""

# EDUCATION değişkeninde resmi dokümantasyonda tanımlanmayan
# 0, 5 ve 6 kodlarını 4 = Others kategorisi altında birleştiriyoruz.
# Bu işlem yalnızca df_clean üzerinde uygulanmaktadır.
# Ham dataframe olan df değişmeden kalmaktadır.

df_clean["EDUCATION"] = df_clean["EDUCATION"].replace({
    0: 4,
    5: 4,
    6: 4
})

# Temizleme işleminden sonra EDUCATION kategorilerini kontrol ediyoruz.
df_clean["EDUCATION"].value_counts().sort_index()

"""### 3.2 MARRIAGE Temizleme Kararı

UCI veri sözlüğünde `MARRIAGE` değişkeni için:

- 1 = Married
- 2 = Single
- 3 = Others

kategorileri tanımlanmaktadır.

Ancak veri setinde ayrıca 0 koduna sahip 54 gözlem bulunmaktadır.
Bu kodun resmi dokümantasyonda açık bir karşılığı bulunmamaktadır.

Gözlem sayısının oldukça düşük olması ve mevcut `3 = Others` kategorisinin
diğer medeni durumları temsil etmesi nedeniyle, `MARRIAGE = 0` gözlemleri
`3 = Others` kategorisi altında birleştirilmiştir.

Bu işlem sırasında herhangi bir gözlem silinmemiştir.
"""

# MARRIAGE değişkeninde resmi dokümantasyonda tanımlanmayan
# 0 kodunu 3 = Others kategorisi altında birleştiriyoruz.
#
# İşlem yalnızca temizleme kopyası olan df_clean üzerinde uygulanmaktadır.
# Ham dataframe olan df değişmeden kalmaktadır.

df_clean["MARRIAGE"] = df_clean["MARRIAGE"].replace({
    0: 3
})

# Temizleme işleminden sonra MARRIAGE kategorilerinin
# beklediğimiz şekilde 1, 2 ve 3 değerlerinden oluştuğunu kontrol ediyoruz.
df_clean["MARRIAGE"].value_counts().sort_index()

"""### 3.3 PAY_X Temizleme Kararı

`PAY_0` ile `PAY_6` arasındaki ödeme durumu değişkenlerinde `-2`, `-1`, `0`
ve pozitif gecikme kodları bulunmaktadır.

Pozitif değerler ödeme gecikmesi seviyelerini temsil ederken, veri setinde
yaygın olarak bulunan `-2` ve `0` kodlarının anlamı resmi UCI
dokümantasyonunda açık biçimde tanımlanmamıştır.

Bu kodlar veri setindeki çok sayıda müşterinin ödeme davranışını temsil ettiği
için eksik değer veya anomali olarak değerlendirilmemiştir.

Bu nedenle PAY_X değişkenleri temizleme aşamasında yeniden kodlanmadan
orijinal halleriyle korunmuştur.

Feature engineering aşamasında pozitif gecikme kodlarından türetilecek
değişkenler ayrıca değerlendirilecektir.
"""

# PAY_X değişkenlerinde herhangi bir temizleme veya yeniden kodlama
# işlemi uygulamadığımızı doğruluyoruz.
# df ham veriyi, df_clean ise temizleme çalışma kopyasını temsil ediyor.

pay_columns_unchanged = df_clean[pay_cols].equals(df[pay_cols])

print("PAY_X kolonları değişmeden korundu:", pay_columns_unchanged)

# Son 6 aya ait fatura tutarı kolonlarını bir liste halinde tanımlıyoruz.
bill_cols = [
    "BILL_AMT1",
    "BILL_AMT2",
    "BILL_AMT3",
    "BILL_AMT4",
    "BILL_AMT5",
    "BILL_AMT6"
]

# Her BILL_AMT kolonunda kaç adet negatif değer bulunduğunu hesaplıyoruz.
# Amaç, negatif tutarların tekil/anormal birkaç gözlem mi
# yoksa veri setinde düzenli şekilde görülen bir durum mu olduğunu anlamaktır.
negative_bill_counts = (df_clean[bill_cols] < 0).sum()

negative_bill_counts

# Negatif fatura tutarlarının her ay içerisindeki yüzde oranını hesaplıyoruz.
# Böylece negatif değerlerin veri setindeki yaygınlığını daha kolay yorumlayabiliriz.
negative_bill_percentages = (
    negative_bill_counts / len(df_clean) * 100
)

negative_bill_percentages.round(2)

# Her müşteri için son 6 ayın herhangi birinde
# negatif BILL_AMT değeri bulunup bulunmadığını kontrol ediyoruz.
#
# Amaç, negatif fatura tutarlarının kaç farklı müşteriyi
# etkilediğini anlamaktır.

has_negative_bill = (df_clean[bill_cols] < 0).any(axis=1)

# En az bir ay negatif fatura bakiyesine sahip müşteri sayısını hesaplıyoruz.
negative_bill_customer_count = has_negative_bill.sum()

# Bu müşterilerin toplam veri setindeki yüzdesini hesaplıyoruz.
negative_bill_customer_percentage = (
    negative_bill_customer_count / len(df_clean) * 100
)

print("En az bir negatif BILL_AMT bulunan müşteri sayısı:",
      negative_bill_customer_count)

print("Toplam müşteriler içindeki oranı:",
      round(negative_bill_customer_percentage, 2), "%")

# Her BILL_AMT değişkeninin minimum değerini inceliyoruz.
# Böylece negatif bakiyelerin büyüklüklerini ay bazında görebileceğiz.

df_clean[bill_cols].min()

"""### 3.4 Negatif BILL_AMT Değerleri

`BILL_AMT1` ile `BILL_AMT6` değişkenlerinde negatif fatura tutarları
bulunduğu görülmüştür.

Ay bazında negatif değer oranı yaklaşık %2 civarında olmakla birlikte,
son 6 ayın en az birinde negatif `BILL_AMT` değerine sahip 1.930 müşteri
bulunmaktadır. Bu değer toplam müşterilerin %6.43'üne karşılık gelmektedir.

Negatif fatura tutarlarının nedeni veri seti dokümantasyonunda açık biçimde
belirtilmemektedir. Finansal verilerde negatif bakiye çeşitli geçerli
hesap hareketlerinden kaynaklanabileceği için, bu değerler doğrudan veri
hatası olarak değerlendirilmemiştir.

Bu nedenle negatif `BILL_AMT` değerleri silinmemiş, sıfıra çevrilmemiş
ve orijinal halleriyle korunmuştur.
"""

# BILL_AMT değişkenlerinde herhangi bir temizleme veya yeniden kodlama
# işlemi uygulamadığımızı doğruluyoruz.

bill_columns_unchanged = df_clean[bill_cols].equals(df[bill_cols])

print(
    "BILL_AMT kolonları değişmeden korundu:",
    bill_columns_unchanged
)

# Son 6 aya ait ödeme tutarı kolonlarını bir liste halinde tanımlıyoruz.
pay_amt_cols = [
    "PAY_AMT1",
    "PAY_AMT2",
    "PAY_AMT3",
    "PAY_AMT4",
    "PAY_AMT5",
    "PAY_AMT6"
]

# PAY_AMT değişkenlerinin üst kuyruk dağılımını inceliyoruz.
# Özellikle 95., 99., 99.5 ve 99.9 yüzdelik değerleri ile maksimumu
# karşılaştırarak çok yüksek ödemelerin ne kadar uç olduğunu anlamaya çalışıyoruz.
#
# Bu aşamada herhangi bir clipping, winsorization veya veri silme işlemi yapmıyoruz.

pay_amt_summary = df_clean[pay_amt_cols].describe(
    percentiles=[0.95, 0.99, 0.995, 0.999]
).T

# Yalnızca karar vermemizde faydalı olacak özet istatistikleri gösteriyoruz.
pay_amt_summary[
    ["mean", "50%", "95%", "99%", "99.5%", "99.9%", "max"]
]

"""### 3.5 PAY_AMT Üst Uç Değerleri

`PAY_AMT1` ile `PAY_AMT6` değişkenlerinin dağılımları incelendiğinde,
yüksek maksimum değerler ve belirgin sağ çarpıklık görülmektedir.

Özellikle maksimum ödeme tutarları, 99.9 yüzdelik değerlerin oldukça
üzerindedir. Ancak yüksek ödeme tutarlarının doğrudan veri hatası olduğunu
gösteren yeterli bir kanıt bulunmamaktadır.

Bu nedenle bu aşamada herhangi bir clipping, winsorization veya gözlem
silme işlemi uygulanmamıştır. Yüksek ödeme tutarları olası geçerli finansal
işlemler olarak korunmuştur.
"""

# PAY_AMT değişkenlerinin sağa çarpık yapısını ve uç değerlerini
# görsel olarak incelemek için boxplot çiziyoruz.
# Tek bir grafikte tüm ödeme tutarı değişkenlerini karşılaştırıyoruz.

plt.figure(figsize=(10, 6))

# PAY_AMT kolonlarını boxplot ile görselleştiriyoruz.
df_clean[pay_amt_cols].boxplot()

# Grafiğin başlık ve eksen isimlerini belirliyoruz.
plt.title("Boxplot of PAY_AMT Variables")
plt.xlabel("PAY_AMT Variables")
plt.ylabel("Payment Amount")

# Grafik elemanlarının düzgün yerleşmesini sağlıyoruz.
plt.tight_layout()

# Grafiği ekranda gösteriyoruz.
plt.show()

"""Yukarıdaki boxplot, `PAY_AMT` değişkenlerinde belirgin bir sağ çarpıklık ve
üst uçta yoğunlaşan aykırı değerler bulunduğunu göstermektedir.

Medyan değerler görece düşük seviyelerde kalırken, bazı gözlemlerde çok yüksek
ödeme tutarları görülmektedir. Bu durum, ödeme tutarı değişkenlerinin dağılımının
simetrik olmadığını ve üst kuyruğun uzun olduğunu desteklemektedir.

Ancak bu yüksek değerlerin doğrudan veri hatası olduğuna dair yeterli kanıt
bulunmadığından, bu aşamada herhangi bir clipping veya gözlem silme işlemi
uygulanmamıştır.
"""

# Her PAY_AMT değişkeninde, ödeme tutarının müşterinin kredi limitinden
# büyük olduğu gözlem sayısını hesaplıyoruz.
#
# Bu durum doğrudan hata anlamına gelmez.
# Ama çok yüksek ödeme değerlerinin ne kadar yaygın olduğunu
# anlamamıza yardımcı olur.

payments_above_limit = pd.Series({
    col: (df_clean[col] > df_clean["LIMIT_BAL"]).sum()
    for col in pay_amt_cols
})

payments_above_limit

# Kredi limitinden yüksek ödeme bulunan gözlemlerin
# toplam müşteri sayısı içindeki yüzdesini hesaplıyoruz.

payments_above_limit_pct = (
    payments_above_limit / len(df_clean) * 100
)

payments_above_limit_pct.round(2)

"""### 3.6 PAY_AMT Temizleme Kararı

`PAY_AMT` değişkenlerinde yüksek üst uç değerler bulunduğu görülmüştür.

Ayrıca bazı müşterilerde ödeme tutarının `LIMIT_BAL` değerinden daha yüksek
olduğu gözlenmiştir. Ancak bu durum ay bazında müşterilerin yalnızca yaklaşık
%0.09-%0.22'sini etkilemektedir.

Ödeme tutarının kredi limitinden yüksek olması tek başına veri hatası olarak
yorumlanmamıştır. Finansal hesap hareketleri, geçmiş bakiye veya toplu ödeme
gibi durumlar bu tür gözlemleri açıklayabilir.

Bu nedenle `PAY_AMT` değişkenlerinde gözlem silme, clipping veya winsorization
uygulanmamış ve orijinal değerler korunmuştur.
"""

# Temizleme işlemleri sonrasında dataframe boyutunu kontrol ediyoruz.
# Herhangi bir gözlem silmediğimiz için 30.000 satırın korunmasını bekliyoruz.
print("Dataframe boyutu:", df_clean.shape)

# Eksik değer oluşup oluşmadığını kontrol ediyoruz.
print("Toplam eksik değer:", df_clean.isnull().sum().sum())

# Duplicate satır oluşup oluşmadığını kontrol ediyoruz.
print("Duplicate satır:", df_clean.duplicated().sum())

# EDUCATION değişkeninin temizlenmiş kategorilerini kontrol ediyoruz.
print("EDUCATION kategorileri:", sorted(df_clean["EDUCATION"].unique()))

# MARRIAGE değişkeninin temizlenmiş kategorilerini kontrol ediyoruz.
print("MARRIAGE kategorileri:", sorted(df_clean["MARRIAGE"].unique()))

"""### 3.7 Veri Temizleme Özeti

Veri temizleme aşamasında ham veri seti korunmuş ve işlemler `df_clean`
isimli çalışma kopyası üzerinde gerçekleştirilmiştir.

Uygulanan değişiklikler:

- `EDUCATION` değişkenindeki dokümante edilmemiş 0, 5 ve 6 kodları
  `4 = Others` kategorisinde birleştirildi.
- `MARRIAGE` değişkenindeki dokümante edilmemiş 0 kodu
  `3 = Others` kategorisinde birleştirildi.

İncelenmesine rağmen değiştirilmeden korunan alanlar:

- `PAY_X` değişkenlerindeki -2 ve 0 kodları
- Negatif `BILL_AMT` değerleri
- `PAY_AMT` değişkenlerindeki yüksek üst uç değerler

Bu değerlerde keyfi silme, clipping veya yeniden kodlama yapılmamıştır.

Temizleme sonrasında:
- Satır sayısı: 30.000
- Kolon sayısı: 25
- Eksik değer: 0
- Duplicate satır: 0
"""

# Temizlenmiş veri setinin kaydedileceği dosya yolunu tanımlıyoruz.
# Ham veri data/raw altında korunmaya devam edecektir.
CLEAN_DATA_PATH = (
    "/content/drive/MyDrive/Credit_Card_Analysis_Project/"
    "data/processed/credit_card_clean.csv"
)

# Temizlenmiş dataframe'i CSV formatında kaydediyoruz.
# index=False kullanarak pandas satır indeksinin ayrı bir kolon olarak
# dosyaya yazılmasını engelliyoruz.
df_clean.to_csv(
    CLEAN_DATA_PATH,
    index=False
)

print("Temiz veri kaydedildi:")
print(CLEAN_DATA_PATH)

# Kaydettiğimiz temiz veri setini yeniden okuyarak
# dosyanın sorunsuz oluşturulduğunu kontrol ediyoruz.
df_clean_check = pd.read_csv(CLEAN_DATA_PATH)

# Boyut ve temel veri kalitesi kontrollerini tekrar yapıyoruz.
print("Boyut:", df_clean_check.shape)
print("Eksik değer:", df_clean_check.isnull().sum().sum())
print("Duplicate:", df_clean_check.duplicated().sum())

# Temizlenen kategorilerin dosyada da doğru kaldığını doğruluyoruz.
print(
    "EDUCATION kategorileri:",
    sorted(df_clean_check["EDUCATION"].unique())
)

print(
    "MARRIAGE kategorileri:",
    sorted(df_clean_check["MARRIAGE"].unique())
)

"""## 4. Key EDA Findings

EDA ve veri temizleme sürecinde öne çıkan temel bulgular aşağıdaki gibidir:

- Hedef değişkende belirgin bir sınıf dengesizliği bulunmaktadır. Müşterilerin %77.88'i default olmazken, %22.12'si default olmuştur. Bu nedenle model performansında yalnızca accuracy metriğine güvenmek uygun değildir.

- Demografik değişkenlerde default oranları arasında bazı farklılıklar gözlenmiştir. Erkek müşterilerde default oranı %24.17, kadın müşterilerde %20.78'dir. Ayrıca ana eğitim gruplarında graduate school → university → high school yönünde default oranının arttığı görülmüştür.

- Yaş gruplarında özellikle 50 yaş ve üzerindeki müşterilerde default oranı yükselme eğilimi göstermektedir. Ancak ileri yaş gruplarındaki örneklem sayıları düşük olduğu için bu sonuçlar temkinli yorumlanmalıdır.

- Geçmiş ödeme davranışı, default riskiyle en güçlü ilişki gösteren alanlardan biridir. En güncel ödeme durumu olan `PAY_0` değişkeninde gecikme seviyesi arttıkça default oranının belirgin şekilde yükseldiği gözlenmiştir.

- Son 6 ayda gecikme yaşanan ay sayısı arttıkça default oranı da güçlü biçimde yükselmektedir. Hiç gecikme yaşamayan müşterilerde default oranı %11.71 iken, 6 ayın tamamında gecikme yaşayan müşterilerde bu oran %70.32'ye çıkmaktadır.

- Veri temizleme aşamasında dokümante edilmemiş `EDUCATION` ve `MARRIAGE` kategorileri mevcut `Others` kategorileri altında birleştirilmiştir. `PAY_X`, negatif `BILL_AMT` ve yüksek `PAY_AMT` değerlerinde ise yeterli kanıt olmadan keyfi dönüşüm yapılmamış ve orijinal değerler korunmuştur.
"""