# -*- coding: utf-8 -*-
"""02_feature_engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LXB8yd08KoBhPB_mr0G-BijmaFBgkcDH

# Credit Card Default Risk — Feature Engineering

### Serra — Feature Engineering

Bu notebookta, daha önce temizlenmiş olan `credit_card_clean.csv` veri seti kullanılacaktır.

Amaç, müşterilerin mevcut bilgileri ve son 6 aylık ödeme davranışlarını kullanarak model için yeni ve anlamlı değişkenler üretmektir.

Bu bölümde:

* Gecikme davranışını gösteren yeni değişkenler oluşturulacaktır.
* Borç ve ödeme bilgilerine dayalı finansal oranlar hesaplanacaktır.
* Son aylardaki finansal değişimler ve trendler incelenecektir.
* Oluşturulan değişkenlerin doğru ve mantıklı olup olmadığı kontrol edilecektir.
* Data Leakage oluşmamasına dikkat edilecektir.

### Temel Kurallar

* `default.payment.next.month` sadece hedef değişkendir, feature üretiminde kullanılmayacaktır.
* `ID` müşteriyi tanımlamak için korunacaktır ancak modele feature olarak verilmeyecektir.
* `PAY_X` kolonlarındaki `-2` ve `0` gibi belirsiz değerler doğrudan ortalama gecikme hesabında kullanılmayacaktır.
* Feature'lar mümkün olduğunca müşterinin kendi geçmiş 6 aylık davranışından üretilecektir.
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

import glob

files = glob.glob(
    "/content/drive/MyDrive/**/data/processed/credit_card_clean.csv",
    recursive=True
)

files

DATA_PATH = files[0]

df = pd.read_csv(DATA_PATH)

print("Dataset shape:", df.shape)
df.head()

"""## 1. Feature Engineering Preparation

Bu bölümde feature engineering aşamasında kullanılacak değişken grupları tanımlanacak ve temizlenmiş veri seti üzerinde çalışmak için ayrı bir çalışma kopyası oluşturulacaktır.

Temizlenmiş veri seti korunacak ve yeni değişkenler `df_fe` çalışma kopyası üzerinde üretilecektir.

"""

# Modelin tahmin etmeye çalışacağı hedef değişkeni tanımlıyoruz.
# Target yalnızca modelleme ve değerlendirme aşamasında kullanılacaktır.
# Feature üretiminde kullanılmayacaktır.
TARGET = "default.payment.next.month"

# Müşteri kimliğini temsil eden ID kolonunu tanımlıyoruz.
# ID kayıtların takibi için korunacak ancak model girdisi olarak kullanılmayacaktır.
ID_COL = "ID"

# Son 6 aya ait ödeme/gecikme durumu kolonlarını bir liste halinde tanımlıyoruz.
# Bu kolonlar gecikme davranışına dayalı yeni feature'ların oluşturulmasında kullanılacaktır.
PAY_STATUS_COLS = [
    "PAY_0",
    "PAY_2",
    "PAY_3",
    "PAY_4",
    "PAY_5",
    "PAY_6"
]

# Son 6 aya ait fatura/borç tutarı kolonlarını tanımlıyoruz.
# Bu kolonlar finansal oran ve trend feature'larında kullanılacaktır.
BILL_COLS = [
    "BILL_AMT1",
    "BILL_AMT2",
    "BILL_AMT3",
    "BILL_AMT4",
    "BILL_AMT5",
    "BILL_AMT6"
]

# Son 6 aya ait yapılan ödeme tutarlarını içeren kolonları tanımlıyoruz.
# Bu kolonlar ödeme davranışı, finansal oranlar ve trend analizlerinde kullanılacaktır.
PAYMENT_COLS = [
    "PAY_AMT1",
    "PAY_AMT2",
    "PAY_AMT3",
    "PAY_AMT4",
    "PAY_AMT5",
    "PAY_AMT6"
]

# Temizlenmiş dataframe'i korumak için feature engineering işlemlerinde
# kullanacağımız ayrı bir çalışma kopyası oluşturuyoruz.
#
# Böylece df üzerinde doğrudan değişiklik yapmıyoruz ve
# oluşturacağımız tüm yeni feature'ları df_fe üzerinde tutuyoruz.

df_fe = df.copy()

# Kopyanın doğru oluşturulduğunu ve başlangıç boyutunun
# değişmediğini kontrol ediyoruz.
df_fe.shape

"""## 2. Delay Behavior Features

Bu bölümde müşterilerin son 6 aylık ödeme geçmişi kullanılarak gecikme davranışını özetleyen yeni değişkenler oluşturulacaktır.

`PAY_X` kolonlarında `-2` ve `0` gibi anlamı net olmayan kodlar bulunduğu için bu değerlerin doğrudan ortalaması alınmayacaktır.

Bunun yerine yalnızca pozitif `PAY_X` değerleri gecikme göstergesi olarak kullanılacaktır.

Oluşturulacak başlıca değişkenler:

* Son 6 ayda kaç ay gecikme olduğu
* En az bir gecikme olup olmadığı
* Görülen en yüksek pozitif gecikme seviyesi
* Son dönemde gecikme olup olmadığı
* Son 3 ay ve önceki 3 ay gecikme sayıları
* Gecikme davranışındaki değişim

"""

# Son 6 ay içinde kaç ayda pozitif gecikme kodu bulunduğunu hesaplıyoruz.
#
# PAY_X > 0 olması gecikme olarak kabul edilmektedir.
# -2, -1 ve 0 değerlerine ayrıca bir gecikme anlamı yüklenmemektedir.
#
# Bu feature EDA aşamasında güçlü bir ilişki göstermiştir:
# gecikmeli ay sayısı arttıkça default oranının da arttığı görülmüştür.

df_fe["delay_month_count"] = (
    (df_fe[PAY_STATUS_COLS] > 0)
    .sum(axis=1)
)

df_fe["delay_month_count"].value_counts().sort_index()

# Müşterinin son 6 ay içerisinde en az bir kez gecikip gecikmediğini gösteriyoruz.
#
# 0 = Son 6 ayda pozitif gecikme yok
# 1 = Son 6 ayda en az bir pozitif gecikme var

df_fe["has_delay"] = (
    df_fe["delay_month_count"] > 0
).astype(int)

df_fe["has_delay"].value_counts()

# Son 6 ayda görülen en yüksek pozitif gecikme seviyesini hesaplıyoruz.
#
# Negatif PAY_X değerleri gecikme seviyesi olarak yorumlanmadığı için
# bu hesaplamada 0'a çekilmektedir.
#
# Örneğin:
# [-1, 0, 2, 0, 3, -2] -> max_positive_delay = 3

positive_delay_values = df_fe[PAY_STATUS_COLS].clip(lower=0)

df_fe["max_positive_delay"] = positive_delay_values.max(axis=1)

df_fe["max_positive_delay"].value_counts().sort_index()

# En güncel ödeme döneminde gecikme olup olmadığını gösteriyoruz.
#
# PAY_0 > 0 ise müşteri en güncel dönemde gecikmiş kabul edilmektedir.
#
# 0 = Güncel dönemde gecikme yok
# 1 = Güncel dönemde gecikme var

df_fe["recent_delay"] = (
    df_fe["PAY_0"] > 0
).astype(int)

df_fe["recent_delay"].value_counts()

# Gecikme davranışının zaman içinde değişip değişmediğini incelemek için
# son 6 aylık ödeme geçmişini iki döneme ayırıyoruz.

RECENT_PAY_COLS = [
    "PAY_0",
    "PAY_2",
    "PAY_3"
]

OLDER_PAY_COLS = [
    "PAY_4",
    "PAY_5",
    "PAY_6"
]

# Son 3 ayda kaç ay gecikme yaşandığını hesaplıyoruz.

df_fe["recent_3m_delay_count"] = (
    (df_fe[RECENT_PAY_COLS] > 0)
    .sum(axis=1)
)

# Önceki 3 ayda kaç ay gecikme yaşandığını hesaplıyoruz.

df_fe["older_3m_delay_count"] = (
    (df_fe[OLDER_PAY_COLS] > 0)
    .sum(axis=1)
)

df_fe[
    ["recent_3m_delay_count", "older_3m_delay_count"]
].head()

# Son 3 ay ile önceki 3 ay arasındaki gecikme sayısı farkını hesaplıyoruz.
#
# Pozitif değer:
# Son dönemde gecikme sayısı artmış olabilir.
#
# Negatif değer:
# Son dönemde gecikme sayısı azalmış olabilir.
#
# 0:
# İki dönemdeki gecikme sayısı aynıdır.

df_fe["delay_count_change"] = (
    df_fe["recent_3m_delay_count"]
    - df_fe["older_3m_delay_count"]
)

df_fe["delay_count_change"].value_counts().sort_index()

# Oluşturulan gecikme feature'larını birlikte kontrol ediyoruz.

delay_features = [
    "delay_month_count",
    "has_delay",
    "max_positive_delay",
    "recent_delay",
    "recent_3m_delay_count",
    "older_3m_delay_count",
    "delay_count_change"
]

df_fe[
    ["ID"] + PAY_STATUS_COLS + delay_features
].head(10)

df_fe.shape

"""## 3. Financial Ratio Features

Bu bölümde müşterilerin borç, ödeme ve kredi limiti bilgileri kullanılarak finansal davranışı özetleyen yeni feature'lar oluşturulacaktır.

Oran hesaplamalarına başlamadan önce `BILL_AMT` değerlerindeki sıfır ve negatif tutarlar incelenecektir.

Sıfır veya negatif borç tutarlarında doğrudan bölme işlemi yapılmayacak ve paydaya keyfi olarak `+1` eklenmeyecektir.
"""

# Finansal oranlarda payda olarak kullanılabilecek BILL_AMT kolonlarını
# önce sıfır ve negatif değerler açısından kontrol ediyoruz.
#
# Amaç:
# - Kaç müşteride BILL_AMT = 0 olduğunu görmek
# - Kaç müşteride BILL_AMT < 0 olduğunu görmek
# - Oran hesaplamalarında hangi durumlara özel işlem gerektiğini belirlemek

bill_value_check = pd.DataFrame({
    "negative_count": (df_fe[BILL_COLS] < 0).sum(),
    "zero_count": (df_fe[BILL_COLS] == 0).sum(),
    "positive_count": (df_fe[BILL_COLS] > 0).sum()
})

bill_value_check

# Kredi limitinin oran hesaplamalarında güvenli bir payda olup olmadığını
# kontrol ediyoruz.

print("LIMIT_BAL <= 0 müşteri sayısı:",
      (df_fe["LIMIT_BAL"] <= 0).sum())

print("Minimum LIMIT_BAL:",
      df_fe["LIMIT_BAL"].min())

# Her müşterinin son 6 ayındaki BILL_AMT değerlerinden
# kaç tanesinin pozitif olduğunu hesaplıyoruz.
#
# Bu bilgiyi daha sonra ödeme / borç oranlarını oluştururken
# yalnızca anlamlı dönemleri kullanabilmek için değerlendirebiliriz.

df_fe["positive_bill_month_count"] = (
    (df_fe[BILL_COLS] > 0)
    .sum(axis=1)
)

df_fe["positive_bill_month_count"].value_counts().sort_index()

"""### 3.1. Ortalama Borç ve Ödeme Davranışı

Müşterilerin son 6 aylık borç ve ödeme tutarlarını tek bir özet değerde göstermek için ortalama borç ve ortalama ödeme feature'ları oluşturulacaktır.

Negatif `BILL_AMT` değerleri veri setinde bilinçli olarak korunduğu için ham veri değiştirilmemektedir.
"""

# Müşterinin son 6 aylık ortalama fatura/borç tutarını hesaplıyoruz.
#
# Negatif BILL_AMT değerlerini burada silmiyoruz veya değiştirmiyoruz.
# Bu feature müşterinin 6 aylık ortalama net hesap bakiyesini özetlemektedir.

df_fe["avg_bill_amt"] = df_fe[BILL_COLS].mean(axis=1)


# Müşterinin son 6 ayda yaptığı ortalama ödeme tutarını hesaplıyoruz.

df_fe["avg_payment_amt"] = df_fe[PAYMENT_COLS].mean(axis=1)


# İlk birkaç müşteriyi kontrol ediyoruz.

df_fe[
    ["ID", "avg_bill_amt", "avg_payment_amt"]
].head()

# Negatif BILL_AMT değerlerini yalnızca bu hesaplama için 0 olarak ele alıyoruz.
# Ham BILL_AMT kolonları değiştirilmemektedir.

positive_bill_values = df_fe[BILL_COLS].clip(lower=0)

# Son 6 aylık ortalama pozitif borç tutarı
df_fe["avg_positive_bill_amt"] = positive_bill_values.mean(axis=1)

# Ortalama pozitif borcun kredi limitine oranı
df_fe["avg_utilization_ratio"] = (
    df_fe["avg_positive_bill_amt"]
    / df_fe["LIMIT_BAL"]
)

# Kontrol
df_fe[
    ["ID", "LIMIT_BAL", "avg_positive_bill_amt", "avg_utilization_ratio"]
].head()

# Oluşturulan finansal feature'ların dağılımlarını kontrol ediyoruz.

df_fe[
    [
        "avg_bill_amt",
        "avg_payment_amt",
        "avg_positive_bill_amt",
        "avg_utilization_ratio"
    ]
].describe().T

# Ortalama borcu kredi limitini aşan müşterilerin sayısını kontrol ediyoruz.

print(
    "avg_utilization_ratio > 1 müşteri sayısı:",
    (df_fe["avg_utilization_ratio"] > 1).sum()
)

print(
    "Oranı:",
    (df_fe["avg_utilization_ratio"] > 1).mean()
)

"""`avg_utilization_ratio > 1` olan 638 müşteri bulunmaktadır. Bu grup toplam müşterilerin yaklaşık %2.13'ünü oluşturmaktadır. Bu değerler silinmemiştir; potansiyel olarak önemli bir risk sinyali olabileceği için feature içinde korunmuştur.

### 3.3. Ödeme / BILL_AMT Oranı

Müşterinin yaptığı ödemenin ilgili dönemdeki pozitif BILL_AMT bakiyesine oranı hesaplanacaktır.

`BILL_AMT` değeri 0 veya negatif olan dönemlerde oran hesaplanmayacaktır. Böylece sıfıra bölme problemi ve anlamı belirsiz oranlar önlenmiş olacaktır.

Paydaya keyfi olarak `+1` eklenmeyecektir.
"""

# Her ay için PAY_AMT / BILL_AMT oranını hesaplıyoruz.
#
# Oran yalnızca BILL_AMT > 0 olduğunda hesaplanmaktadır.
# BILL_AMT <= 0 olan dönemler NaN bırakılmaktadır.
#
# Ham BILL_AMT ve PAY_AMT kolonları değiştirilmemektedir.

payment_bill_ratio_cols = []

for i in range(6):
    bill_col = BILL_COLS[i]
    payment_col = PAYMENT_COLS[i]
    ratio_col = f"payment_bill_ratio_{i+1}"

    df_fe[ratio_col] = np.where(
        df_fe[bill_col] > 0,
        df_fe[payment_col] / df_fe[bill_col],
        np.nan
    )

    payment_bill_ratio_cols.append(ratio_col)

# Oluşturulan aylık ödeme / BILL_AMT oranlarını kontrol ediyoruz.

df_fe[
    ["ID"] + payment_bill_ratio_cols
].head(10)

"""### 3.4. Toplam Ödeme / Pozitif BILL_AMT Oranı

Aylık ödeme/BILL_AMT oranlarında küçük BILL_AMT değerleri çok yüksek oranlara neden olabilmektedir.

Bu nedenle müşterinin genel ödeme davranışını daha dengeli temsil etmek için, BILL_AMT > 0 olan dönemlerdeki toplam ödeme tutarı toplam pozitif BILL_AMT tutarına bölünmüştür.
"""

# Son 6 ayda yapılan toplam ödeme tutarı
total_payment = df_fe[PAYMENT_COLS].sum(axis=1)

# Pozitif BILL_AMT değerlerinin toplamı
total_positive_bill = positive_bill_values.sum(axis=1)

# Toplam ödeme / toplam pozitif BILL_AMT oranı
# Pozitif BILL_AMT toplamı 0 ise oran hesaplanmıyor.
df_fe["total_payment_to_bill_ratio"] = np.where(
    total_positive_bill > 0,
    total_payment / total_positive_bill,
    np.nan
)

df_fe[
    ["ID", "total_payment_to_bill_ratio"]
].head(10)

# Toplam ödeme / pozitif BILL_AMT oranının
# 30.000 müşteri üzerindeki dağılımını inceliyoruz.

df_fe["total_payment_to_bill_ratio"].describe()

# Pozitif BILL_AMT bulunmadığı için oranı hesaplanamayan
# müşteri sayısını kontrol ediyoruz.

print(
    "Oranı hesaplanamayan müşteri sayısı:",
    df_fe["total_payment_to_bill_ratio"].isna().sum()
)

"""Toplam 966 müşteri için pozitif BILL_AMT bulunmadığından `total_payment_to_bill_ratio` hesaplanamamış ve bu değerler NaN olarak bırakılmıştır. Sıfıra bölme veya keyfi bir +1 düzeltmesi uygulanmamıştır."""

for threshold in [1, 2, 5, 10]:
    count = (df_fe["total_payment_to_bill_ratio"] > threshold).sum()
    rate = count / df_fe["total_payment_to_bill_ratio"].notna().sum()

    print(
        f"Ratio > {threshold}: {count} müşteri "
        f"(%{rate * 100:.2f})"
    )

"""### 3.5. Ödeme / BILL_AMT Oranının Log Dönüşümü

`total_payment_to_bill_ratio` değişkeninde az sayıda çok yüksek değer bulunduğu görülmüştür.

Bu değerler veri setinden silinmemiş veya kırpılmamıştır. Bunun yerine uç değerlerin etkisini azaltmak amacıyla log dönüşümlü alternatif bir feature oluşturulacaktır.

Bu dönüşüm target değişkenini kullanmadığı ve veriden herhangi bir parametre öğrenmediği için leakage oluşturmaz.
"""

# total_payment_to_bill_ratio değerleri 0 veya pozitif olduğu için
# log1p dönüşümünü güvenli şekilde uyguluyoruz.
#
# log1p(x) = log(1 + x)
#
# Çok büyük değerleri sıkıştırırken küçük değerlerin sırasını korur.
# NaN değerler yine NaN olarak kalacaktır.

df_fe["log_total_payment_to_bill_ratio"] = np.log1p(
    df_fe["total_payment_to_bill_ratio"]
)

# Ham oran ile log dönüşümlü oranı birlikte kontrol ediyoruz.

df_fe[
    [
        "ID",
        "total_payment_to_bill_ratio",
        "log_total_payment_to_bill_ratio"
    ]
].head(10)

"""Log dönüşümü sonrasında düşük ödeme/BILL_AMT oranları büyük ölçüde korunurken, yüksek ve uç değerler sıkıştırılmıştır. Ham oran da veri setinde korunmuştur.

## 4. Financial Trend Features

Bu bölümde müşterilerin son 6 aylık finansal davranışlarının zaman içinde nasıl değiştiği incelenecektir.

Amaç yalnızca ortalama borç ve ödeme seviyesini değil, müşterinin son dönemdeki davranışının önceki döneme göre artıp artmadığını veya azalıp azalmadığını gösterebilen yeni feature'lar oluşturmaktır.

Bu kapsamda son 3 ay ile önceki 3 ayın BILL_AMT ve PAY_AMT değerleri karşılaştırılacaktır.
"""

# Son 6 aylık BILL_AMT değerlerini iki döneme ayırıyoruz.
#
# BILL_AMT1-3 = daha yakın dönem
# BILL_AMT4-6 = daha eski dönem

RECENT_BILL_COLS = [
    "BILL_AMT1",
    "BILL_AMT2",
    "BILL_AMT3"
]

OLDER_BILL_COLS = [
    "BILL_AMT4",
    "BILL_AMT5",
    "BILL_AMT6"
]

# Aynı ayrımı ödeme tutarları için de yapıyoruz.

RECENT_PAYMENT_COLS = [
    "PAY_AMT1",
    "PAY_AMT2",
    "PAY_AMT3"
]

OLDER_PAYMENT_COLS = [
    "PAY_AMT4",
    "PAY_AMT5",
    "PAY_AMT6"
]

"""### 4.1. BILL_AMT Trend Features

Müşterinin son 3 aylık BILL_AMT ortalaması ile önceki 3 aylık BILL_AMT ortalaması karşılaştırılacaktır.

Amaç, müşterinin hesap bakiyesinin son dönemde artıp artmadığını veya azalıp azalmadığını özetleyen feature'lar oluşturmaktır.

Negatif BILL_AMT değerleri bu hesaplamada değiştirilmeden korunmaktadır.
"""

# Son 3 aylık ortalama BILL_AMT değerini hesaplıyoruz.

df_fe["recent_3m_avg_bill"] = (
    df_fe[RECENT_BILL_COLS]
    .mean(axis=1)
)

# Önceki 3 aylık ortalama BILL_AMT değerini hesaplıyoruz.

df_fe["older_3m_avg_bill"] = (
    df_fe[OLDER_BILL_COLS]
    .mean(axis=1)
)

# Son dönem ile önceki dönem arasındaki farkı hesaplıyoruz.
#
# Pozitif değer  -> BILL_AMT son dönemde daha yüksek
# Negatif değer  -> BILL_AMT son dönemde daha düşük
# 0              -> İki dönemin ortalaması aynı

df_fe["bill_change_3m"] = (
    df_fe["recent_3m_avg_bill"]
    - df_fe["older_3m_avg_bill"]
)

df_fe[
    [
        "ID",
        "recent_3m_avg_bill",
        "older_3m_avg_bill",
        "bill_change_3m"
    ]
].head(10)

# BILL_AMT değişiminin yönünü sayısal olarak gösteriyoruz.
#
#  1 = Son dönemde BILL_AMT artmış
#  0 = Değişmemiş
# -1 = Son dönemde BILL_AMT azalmış

df_fe["bill_trend_direction"] = np.sign(
    df_fe["bill_change_3m"]
).astype(int)

df_fe["bill_trend_direction"].value_counts().sort_index()

"""### 4.2. Payment Trend Features

Müşterinin son 3 aylık ortalama ödeme tutarı ile önceki 3 aylık ortalama ödeme tutarı karşılaştırılacaktır.

Bu feature'lar müşterinin son dönemde ödeme miktarını artırıp artırmadığını veya azaltıp azaltmadığını göstermeyi amaçlamaktadır.
"""

# Son 3 aylık ortalama ödeme tutarını hesaplıyoruz.

df_fe["recent_3m_avg_payment"] = (
    df_fe[RECENT_PAYMENT_COLS]
    .mean(axis=1)
)

# Önceki 3 aylık ortalama ödeme tutarını hesaplıyoruz.

df_fe["older_3m_avg_payment"] = (
    df_fe[OLDER_PAYMENT_COLS]
    .mean(axis=1)
)

# Son dönem ile önceki dönem arasındaki ödeme farkını hesaplıyoruz.
#
# Pozitif değer -> son dönemde ortalama ödeme artmış
# Negatif değer -> son dönemde ortalama ödeme azalmış

df_fe["payment_change_3m"] = (
    df_fe["recent_3m_avg_payment"]
    - df_fe["older_3m_avg_payment"]
)

df_fe[
    [
        "ID",
        "recent_3m_avg_payment",
        "older_3m_avg_payment",
        "payment_change_3m"
    ]
].head(10)

# Ödeme değişiminin yönünü gösteriyoruz.
#
#  1 = Ortalama ödeme artmış
#  0 = Değişmemiş
# -1 = Ortalama ödeme azalmış

df_fe["payment_trend_direction"] = np.sign(
    df_fe["payment_change_3m"]
).astype(int)

df_fe["payment_trend_direction"].value_counts().sort_index()

"""Müşterilerin büyük bölümünde son 3 aylık ortalama ödeme tutarı önceki 3 aya göre artmıştır. Ancak ödeme artışı tek başına olumlu bir risk göstergesi olarak yorumlanmamış, borç ve gecikme davranışlarıyla birlikte değerlendirilmek üzere feature olarak korunmuştur.

### 4.3. Kredi Limitine Göre BILL_AMT Değişimi

Müşterinin son dönemdeki BILL_AMT değişiminin kredi limitine göre ne kadar büyük olduğunu göstermek amacıyla yeni bir trend feature'ı oluşturulacaktır.

Böylece aynı tutardaki bakiye artışının düşük ve yüksek kredi limitine sahip müşteriler için farklı önemi yakalanabilir.
"""

# Son 3 ay ve önceki 3 ay için pozitif BILL_AMT ortalamalarını hesaplıyoruz.
#
# Negatif BILL_AMT değerleri yalnızca bu kullanım oranı hesabında
# 0 olarak ele alınmaktadır. Ham veri değiştirilmemektedir.

recent_positive_bill = (
    df_fe[RECENT_BILL_COLS]
    .clip(lower=0)
    .mean(axis=1)
)

older_positive_bill = (
    df_fe[OLDER_BILL_COLS]
    .clip(lower=0)
    .mean(axis=1)
)

# Son 3 aylık pozitif BILL_AMT'nin kredi limitine oranı

df_fe["recent_3m_utilization"] = (
    recent_positive_bill / df_fe["LIMIT_BAL"]
)

# Önceki 3 aylık pozitif BILL_AMT'nin kredi limitine oranı

df_fe["older_3m_utilization"] = (
    older_positive_bill / df_fe["LIMIT_BAL"]
)

# Kullanım oranındaki değişimi hesaplıyoruz.
#
# Pozitif değer -> son dönemde limit kullanımı artmış
# Negatif değer -> son dönemde limit kullanımı azalmış

df_fe["utilization_change_3m"] = (
    df_fe["recent_3m_utilization"]
    - df_fe["older_3m_utilization"]
)

df_fe[
    [
        "ID",
        "recent_3m_utilization",
        "older_3m_utilization",
        "utilization_change_3m"
    ]
].head(10)

# Kredi limiti kullanım trendinin genel dağılımını kontrol ediyoruz.

df_fe[
    [
        "recent_3m_utilization",
        "older_3m_utilization",
        "utilization_change_3m"
    ]
].describe().T

"""### 4.4. Kredi Limitine Göre Ödeme Değişimi

Müşterinin ödeme tutarındaki son dönem değişiminin kredi limitine göre büyüklüğünü göstermek amacıyla yeni bir feature oluşturulacaktır.
"""

# Son 3 ay ile önceki 3 ay arasındaki ödeme değişimini
# müşterinin kredi limitine bölerek normalize ediyoruz.
#
# LIMIT_BAL tüm müşterilerde pozitif olduğu için
# güvenli bir payda olarak kullanılmaktadır.

df_fe["payment_change_to_limit"] = (
    df_fe["payment_change_3m"]
    / df_fe["LIMIT_BAL"]
)

df_fe[
    [
        "ID",
        "payment_change_3m",
        "LIMIT_BAL",
        "payment_change_to_limit"
    ]
].head(10)

# Financial Trend bölümünde oluşturulan feature'ları listeliyoruz.

trend_features = [
    "recent_3m_avg_bill",
    "older_3m_avg_bill",
    "bill_change_3m",
    "bill_trend_direction",
    "recent_3m_avg_payment",
    "older_3m_avg_payment",
    "payment_change_3m",
    "payment_trend_direction",
    "recent_3m_utilization",
    "older_3m_utilization",
    "utilization_change_3m",
    "payment_change_to_limit"
]

df_fe[["ID"] + trend_features].head(10)

print("Güncel dataset boyutu:", df_fe.shape)

"""Feature engineering sonrasında gözlem sayısı 30.000 olarak korunmuş, sütun sayısı ise 25'ten 57'ye yükselmiştir. Böylece toplam 32 yeni feature/helper değişken oluşturulmuştur.

# Day 2 — Feature Validation & Leakage Control

## 5. Feature Validation & Leakage Control

Bu bölümde oluşturulan yeni feature'lar kontrol edilecektir.

Amaç:
- Yeni oluşturulan feature'ları belirlemek,
- Eksik ve sonsuz değerleri kontrol etmek,
- Target değişkeninin feature üretiminde kullanılmadığını doğrulamak,
- `ID` değişkenini model girdilerinden ayırmak,
- Modelleme öncesinde veri setinin son durumunu kontrol etmektir.
"""

# Feature engineering öncesindeki orijinal sütunları alıyoruz.

original_cols = df.columns.tolist()

# df_fe içinde sonradan eklenen sütunları belirliyoruz.

engineered_features = [
    col for col in df_fe.columns
    if col not in original_cols
]

print("Orijinal sütun sayısı:", len(original_cols))
print("Yeni oluşturulan feature sayısı:", len(engineered_features))

engineered_features

# Yalnızca oluşturduğumuz yeni feature'lardaki eksik değerleri kontrol ediyoruz.

missing_engineered = (
    df_fe[engineered_features]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

# Sadece gerçekten NaN içeren sütunları gösteriyoruz.

missing_engineered[
    missing_engineered > 0
]

# np.inf veya -np.inf oluşmuş mu kontrol ediyoruz.

numeric_engineered = df_fe[engineered_features].select_dtypes(
    include=np.number
)

inf_counts = pd.Series(
    np.isinf(numeric_engineered).sum(),
    index=numeric_engineered.columns
)

inf_counts[
    inf_counts > 0
]

print("Dataset boyutu:", df_fe.shape)
print("Target mevcut mu:", TARGET in df_fe.columns)
print("ID mevcut mu:", ID_COL in df_fe.columns)
print("Yeni feature sayısı:", len(engineered_features))

"""### 5.2. Eksik ve Sonsuz Değer Kontrolü

Feature engineering sırasında özellikle oran hesaplamalarında bazı değerler bilinçli olarak NaN bırakılmıştır.

Bu bölümde yeni feature'larda bulunan NaN ve sonsuz (`inf`) değerler kontrol edilmektedir. NaN değerler bu aşamada doldurulmayacaktır; imputasyon gerekiyorsa modelleme aşamasında yalnızca training data üzerinden uygulanacaktır.
"""

# Yeni oluşturulan feature'lardaki NaN sayılarını kontrol ediyoruz.

missing_engineered = (
    df_fe[engineered_features]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

missing_engineered[missing_engineered > 0]

# Yeni feature'larda sonsuz değer oluşmuş mu kontrol ediyoruz.

numeric_engineered = df_fe[
    engineered_features
].select_dtypes(include=np.number)

inf_counts = pd.Series(
    np.isinf(numeric_engineered).sum(),
    index=numeric_engineered.columns
)

inf_counts[inf_counts > 0]

# ID müşteri eşleştirmesi için korunacaktır ancak modele verilmeyecektir.
# Target ise tahmin edilmek istenen değişkendir ve X içerisinde bulunmamalıdır.

model_candidate_cols = [
    col for col in df_fe.columns
    if col not in [ID_COL, TARGET]
]

print("Toplam sütun:", df_fe.shape[1])
print("Model için aday sütun sayısı:", len(model_candidate_cols))
print("ID model feature'larında mı?:", ID_COL in model_candidate_cols)
print("Target model feature'larında mı?:", TARGET in model_candidate_cols)

"""### 5.3. Model Girdilerinin Ayrılması

`ID` yalnızca müşteri eşleştirmesi amacıyla veri setinde korunmaktadır ve model girdisi olarak kullanılmayacaktır.

`default.payment.next.month` hedef değişkeni de model girdilerinden ayrılmıştır.

Bu kontroller sonucunda 57 sütunun 55'i model için aday değişken olarak kalmıştır.
"""

# Delay feature listesini yeniden tanımlıyoruz.

delay_features = [
    "delay_month_count",
    "has_delay",
    "max_positive_delay",
    "recent_delay",
    "recent_3m_delay_count",
    "older_3m_delay_count",
    "delay_count_change"
]

# Aylık ödeme / BILL_AMT oran feature'ları

payment_bill_ratio_cols = [
    "payment_bill_ratio_1",
    "payment_bill_ratio_2",
    "payment_bill_ratio_3",
    "payment_bill_ratio_4",
    "payment_bill_ratio_5",
    "payment_bill_ratio_6"
]

# Trend feature'ları

trend_features = [
    "recent_3m_avg_bill",
    "older_3m_avg_bill",
    "bill_change_3m",
    "bill_trend_direction",
    "recent_3m_avg_payment",
    "older_3m_avg_payment",
    "payment_change_3m",
    "payment_trend_direction",
    "recent_3m_utilization",
    "older_3m_utilization",
    "utilization_change_3m",
    "payment_change_to_limit"
]

# Feature Engineering sonucunda oluşturulan değişkenleri
# kategorilerine göre kontrol ediyoruz.

print("Delay Features:")
print(delay_features)

print("\nFinancial / Ratio Features:")
financial_features = [
    "positive_bill_month_count",
    "avg_bill_amt",
    "avg_payment_amt",
    "avg_positive_bill_amt",
    "avg_utilization_ratio",
    *payment_bill_ratio_cols,
    "total_payment_to_bill_ratio",
    "log_total_payment_to_bill_ratio"
]
print(financial_features)

print("\nTrend Features:")
print(trend_features)

print(
    "\nToplam engineered feature:",
    len(delay_features) +
    len(financial_features) +
    len(trend_features)
)

"""Feature engineering sonucunda toplam 32 yeni değişken oluşturulmuştur:
- 7 Delay Behavior feature
- 13 Financial / Ratio feature
- 12 Financial Trend feature

Yeni oluşturulan değişkenlerin tamamı kontrol edilmiş ve feature gruplarıyla eşleştirilmiştir.
"""

# Yeni feature'lardaki eksik değerleri kontrol ediyoruz.

missing_engineered = (
    df_fe[engineered_features]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

missing_engineered[missing_engineered > 0]

"""Yeni oluşturulan oran değişkenlerindeki eksik değerler incelenmiştir.

Aylık `payment_bill_ratio` değişkenlerindeki NaN değerler, ilgili ayda `BILL_AMT <= 0` olması nedeniyle bilinçli olarak oluşmaktadır.

`total_payment_to_bill_ratio` ve log dönüşümlü versiyonunda 966 müşteride oran hesaplanamamıştır. Bu değerler sıfıra bölme veya keyfi bir düzeltme yapılmadan NaN olarak korunmuştur.
"""

numeric_engineered = df_fe[
    engineered_features
].select_dtypes(include=np.number)

inf_counts = pd.Series(
    np.isinf(numeric_engineered).sum(),
    index=numeric_engineered.columns
)

inf_counts[inf_counts > 0]

"""Yeni oluşturulan feature'larda sonsuz (`+inf` / `-inf`) değer bulunmamıştır."""

# Aylık payment/BILL_AMT oranlarını final model adaylarından çıkarıyoruz.
# Toplam ve log dönüşümlü oranlar korunacaktır.

excluded_engineered_features = payment_bill_ratio_cols

selected_engineered_features = [
    col for col in engineered_features
    if col not in excluded_engineered_features
]

print("Toplam engineered feature:", len(engineered_features))
print("Final engineered feature adayı:", len(selected_engineered_features))
print("Çıkarılan feature sayısı:", len(excluded_engineered_features))

# Orijinal değişkenlerden ID ve target çıkarılıyor.
# Ardından seçilen engineered feature'lar ekleniyor.

original_model_features = [
    col for col in original_cols
    if col not in [ID_COL, TARGET]
]

final_model_features = (
    original_model_features
    + selected_engineered_features
)

print("Final model feature sayısı:", len(final_model_features))
print("ID içeriyor mu?:", ID_COL in final_model_features)
print("Target içeriyor mu?:", TARGET in final_model_features)

"""Final model aday setinde 49 feature bulunmaktadır. `ID` yalnızca müşteri eşleştirmesi amacıyla tutulmuş, target değişkeni ise model girdilerinden çıkarılmıştır.

## 6. Final Feature Dataset

Feature validation sonrasında aylık `payment_bill_ratio_1-6` değişkenleri final aday setinden çıkarılmıştır.

`ID` müşteri eşleştirmesi için, `default.payment.next.month` ise target olarak veri setinde korunacaktır. Ancak bu iki değişken model feature'larının içinde yer almamaktadır.

Eksik oran değerleri bu aşamada doldurulmamıştır. Gerekli imputasyon işlemleri modelleme aşamasında yalnızca training data üzerinden uygulanacaktır.
"""

# Burak'a aktarılacak final veri setini oluşturuyoruz.
#
# ID: müşteri eşleştirmesi için tutuluyor.
# final_model_features: modele aday değişkenler.
# TARGET: tahmin edilmek istenen değişken.

df_final = df_fe[
    [ID_COL] + final_model_features + [TARGET]
].copy()

print("Final dataset boyutu:", df_final.shape)
print("Toplam müşteri:", df_final.shape[0])
print("Toplam sütun:", df_final.shape[1])

# Final dataset'te eksik değer bulunan sütunları kontrol ediyoruz.

final_missing = (
    df_final
    .isna()
    .sum()
    .sort_values(ascending=False)
)

final_missing[final_missing > 0]

import os

# Clean dataset'in bulunduğu processed klasörünü kullanıyoruz.

OUTPUT_PATH = os.path.join(
    os.path.dirname(DATA_PATH),
    "credit_card_features.csv"
)

df_final.to_csv(
    OUTPUT_PATH,
    index=False
)

print("Dosya kaydedildi:")
print(OUTPUT_PATH)

print("Dosya mevcut mu?:", os.path.exists(OUTPUT_PATH))

check_df = pd.read_csv(OUTPUT_PATH)

print("Kaydedilen dataset boyutu:", check_df.shape)

"""### Sonuç

Feature engineering ve temel validation işlemleri tamamlanmıştır.

- 30.000 gözlem korunmuştur.
- Toplam 32 yeni feature/helper değişken üretilmiştir.
- Aylık `payment_bill_ratio_1-6` değişkenleri final model aday setinden çıkarılmıştır.
- Final model aday setinde 49 feature bulunmaktadır.
- `ID` ve target model girdilerinden ayrılmıştır.
- Final dataset 30.000 satır ve 51 sütun olarak `credit_card_features.csv` dosyasına kaydedilmiştir.

# Day 3 — Feature Engineering Pipeline
## 7. Feature Engineering Pipeline

Bu bölümde önceki aşamalarda oluşturulan feature engineering adımları tekrar kullanılabilir bir fonksiyon içerisinde birleştirilecektir.

Amaç, temiz veri seti verildiğinde aynı feature'ların her seferinde aynı kurallarla otomatik olarak oluşturulmasını sağlamaktır.

Pipeline içerisinde target değişkeni feature üretiminde kullanılmayacak ve ham değişkenler değiştirilmeyecektir.
"""

# Pipeline içerisinde kullanılacak temel sütun gruplarını tanımlıyoruz.

TARGET = "default.payment.next.month"
ID_COL = "ID"

PAY_STATUS_COLS = [
    "PAY_0", "PAY_2", "PAY_3",
    "PAY_4", "PAY_5", "PAY_6"
]

BILL_COLS = [
    "BILL_AMT1", "BILL_AMT2", "BILL_AMT3",
    "BILL_AMT4", "BILL_AMT5", "BILL_AMT6"
]

PAYMENT_COLS = [
    "PAY_AMT1", "PAY_AMT2", "PAY_AMT3",
    "PAY_AMT4", "PAY_AMT5", "PAY_AMT6"
]

RECENT_PAY_COLS = ["PAY_0", "PAY_2", "PAY_3"]
OLDER_PAY_COLS = ["PAY_4", "PAY_5", "PAY_6"]

RECENT_BILL_COLS = [
    "BILL_AMT1", "BILL_AMT2", "BILL_AMT3"
]

OLDER_BILL_COLS = [
    "BILL_AMT4", "BILL_AMT5", "BILL_AMT6"
]

RECENT_PAYMENT_COLS = [
    "PAY_AMT1", "PAY_AMT2", "PAY_AMT3"
]

OLDER_PAYMENT_COLS = [
    "PAY_AMT4", "PAY_AMT5", "PAY_AMT6"
]

def build_features(df_input):
    # Orijinal dataframe'in değiştirilmemesi için kopyasını alıyoruz.
    df_out = df_input.copy()

    # ------------------------------------------------
    # 1. Delay Behavior Features
    # ------------------------------------------------

    df_out["delay_month_count"] = (
        (df_out[PAY_STATUS_COLS] > 0).sum(axis=1)
    )

    df_out["has_delay"] = (
        df_out["delay_month_count"] > 0
    ).astype(int)

    positive_delay_values = (
        df_out[PAY_STATUS_COLS]
        .clip(lower=0)
    )

    df_out["max_positive_delay"] = (
        positive_delay_values.max(axis=1)
    )

    df_out["recent_delay"] = (
        df_out["PAY_0"] > 0
    ).astype(int)

    df_out["recent_3m_delay_count"] = (
        (df_out[RECENT_PAY_COLS] > 0).sum(axis=1)
    )

    df_out["older_3m_delay_count"] = (
        (df_out[OLDER_PAY_COLS] > 0).sum(axis=1)
    )

    df_out["delay_count_change"] = (
        df_out["recent_3m_delay_count"]
        - df_out["older_3m_delay_count"]
    )

    # ------------------------------------------------
    # 2. Financial / Ratio Features
    # ------------------------------------------------

    df_out["positive_bill_month_count"] = (
        (df_out[BILL_COLS] > 0).sum(axis=1)
    )

    df_out["avg_bill_amt"] = (
        df_out[BILL_COLS].mean(axis=1)
    )

    df_out["avg_payment_amt"] = (
        df_out[PAYMENT_COLS].mean(axis=1)
    )

    # Negatif BILL_AMT değerleri yalnızca bu hesaplamada 0 yapılır.
    # Orijinal BILL_AMT sütunları değiştirilmez.
    positive_bill_values = (
        df_out[BILL_COLS].clip(lower=0)
    )

    df_out["avg_positive_bill_amt"] = (
        positive_bill_values.mean(axis=1)
    )

    df_out["avg_utilization_ratio"] = (
        df_out["avg_positive_bill_amt"]
        / df_out["LIMIT_BAL"]
    )

    # Aylık ödeme / BILL_AMT oranları
    payment_bill_ratio_cols = []

    for i in range(6):
        bill_col = BILL_COLS[i]
        payment_col = PAYMENT_COLS[i]
        ratio_col = f"payment_bill_ratio_{i+1}"

        df_out[ratio_col] = np.where(
            df_out[bill_col] > 0,
            df_out[payment_col] / df_out[bill_col],
            np.nan
        )

        payment_bill_ratio_cols.append(ratio_col)

    # Toplam ödeme / toplam pozitif BILL_AMT oranı
    total_payment = df_out[PAYMENT_COLS].sum(axis=1)
    total_positive_bill = positive_bill_values.sum(axis=1)

    df_out["total_payment_to_bill_ratio"] = np.where(
        total_positive_bill > 0,
        total_payment / total_positive_bill,
        np.nan
    )

    # Uç değerlerin etkisini azaltmak için log dönüşümü
    df_out["log_total_payment_to_bill_ratio"] = np.log1p(
        df_out["total_payment_to_bill_ratio"]
    )

    # ------------------------------------------------
    # 3. Financial Trend Features
    # ------------------------------------------------

    df_out["recent_3m_avg_bill"] = (
        df_out[RECENT_BILL_COLS].mean(axis=1)
    )

    df_out["older_3m_avg_bill"] = (
        df_out[OLDER_BILL_COLS].mean(axis=1)
    )

    df_out["bill_change_3m"] = (
        df_out["recent_3m_avg_bill"]
        - df_out["older_3m_avg_bill"]
    )

    df_out["bill_trend_direction"] = np.sign(
        df_out["bill_change_3m"]
    ).astype(int)

    df_out["recent_3m_avg_payment"] = (
        df_out[RECENT_PAYMENT_COLS].mean(axis=1)
    )

    df_out["older_3m_avg_payment"] = (
        df_out[OLDER_PAYMENT_COLS].mean(axis=1)
    )

    df_out["payment_change_3m"] = (
        df_out["recent_3m_avg_payment"]
        - df_out["older_3m_avg_payment"]
    )

    df_out["payment_trend_direction"] = np.sign(
        df_out["payment_change_3m"]
    ).astype(int)

    recent_positive_bill = (
        df_out[RECENT_BILL_COLS]
        .clip(lower=0)
        .mean(axis=1)
    )

    older_positive_bill = (
        df_out[OLDER_BILL_COLS]
        .clip(lower=0)
        .mean(axis=1)
    )

    df_out["recent_3m_utilization"] = (
        recent_positive_bill / df_out["LIMIT_BAL"]
    )

    df_out["older_3m_utilization"] = (
        older_positive_bill / df_out["LIMIT_BAL"]
    )

    df_out["utilization_change_3m"] = (
        df_out["recent_3m_utilization"]
        - df_out["older_3m_utilization"]
    )

    df_out["payment_change_to_limit"] = (
        df_out["payment_change_3m"]
        / df_out["LIMIT_BAL"]
    )

    return df_out

df_pipeline_test = build_features(df)

df_pipeline_test[
    ["ID", "total_payment_to_bill_ratio"]
].head(10)

# Temiz dataset üzerinden pipeline'ı çalıştırıyoruz.

df_pipeline = build_features(df)

print("Clean dataset:", df.shape)
print("Pipeline sonrası:", df_pipeline.shape)

"""Pipeline testi başarıyla tamamlanmıştır. Temiz veri setindeki 30.000 gözlem korunmuş ve 25 sütunlu veri, 32 yeni feature eklenerek 57 sütuna çıkarılmıştır.

## 7.1. Feature Engineering Pipeline Kontrolü
Bu bölümde oluşturulan pipeline çıktısının, daha önce adım adım oluşturulan feature'larla aynı sonuçları üretip üretmediği kontrol edilmektedir.
"""

feature_cols = [
    col for col in df_fe.columns
    if col not in ["ID", "default.payment.next.month"]
]

comparison = df_fe[feature_cols].equals(
    df_pipeline_test[feature_cols]
)

print("Manual ve pipeline feature'ları aynı mı?:", comparison)

# Pipeline ile üretilen feature'ların önceki df_fe ile
# aynı olup olmadığını kontrol ediyoruz.

comparison_result = (
    df_fe[engineered_features]
    .equals(df_pipeline[engineered_features])
)

print("Pipeline çıktısı önceki feature'larla tamamen aynı mı?:",
      comparison_result)

# Her iki dataframe'de de aynı engineered feature'lar mevcut mu?

print(
    "Engineered feature sayısı:",
    len(engineered_features)
)

print(
    "Pipeline'da eksik engineered feature var mı?:",
    [
        col for col in engineered_features
        if col not in df_pipeline.columns
    ]
)

"""Pipeline kontrolü sonucunda 32 engineered feature'ın tamamının pipeline içerisinde üretildiği ve eksik feature bulunmadığı doğrulanmıştır.

## 7.2. Final Dataset'in Pipeline ile Oluşturulması

Feature engineering pipeline'ı ile oluşturulan değişkenlerden modelleme için kullanılacak final veri seti hazırlanacaktır.

Aylık `payment_bill_ratio_1-6` değişkenleri final model setine dahil edilmeyecek; `ID` ve target ise veri setinde korunacak ancak model feature'ı olarak kullanılmayacaktır.
"""

# Final dataset'i otomatik hazırlayan fonksiyon

def build_final_dataset(df_input):

    # Önce feature engineering pipeline'ını çalıştırıyoruz.
    df_features = build_features(df_input)

    # Final sette kullanmayacağımız aylık oran feature'ları
    excluded_features = [
        "payment_bill_ratio_1",
        "payment_bill_ratio_2",
        "payment_bill_ratio_3",
        "payment_bill_ratio_4",
        "payment_bill_ratio_5",
        "payment_bill_ratio_6"
    ]

    # ID ve target hariç model feature'larını belirliyoruz.
    final_model_features = [
        col for col in df_features.columns
        if col not in excluded_features + [ID_COL, TARGET]
    ]

    # ID ve target veri setinde korunuyor.
    df_final_pipeline = df_features[
        [ID_COL] + final_model_features + [TARGET]
    ].copy()

    return df_final_pipeline, final_model_features

df_final_pipeline, final_model_features_pipeline = build_final_dataset(df)

print("Final pipeline dataset boyutu:", df_final_pipeline.shape)
print("Model feature sayısı:", len(final_model_features_pipeline))
print("ID model feature'larında mı?:",
      ID_COL in final_model_features_pipeline)
print("Target model feature'larında mı?:",
      TARGET in final_model_features_pipeline)

"""### 7.3. Final Pipeline Kontrolü

Pipeline ile otomatik olarak oluşturulan final dataset'in, daha önce manuel adımlarla hazırlanan final dataset ile aynı sonucu üretip üretmediği kontrol edilecektir.
"""

# Pipeline ile oluşturulan final dataset ile
# daha önce hazırlanan df_final'i karşılaştırıyoruz.

same_shape = df_final.shape == df_final_pipeline.shape

same_columns = (
    df_final.columns.tolist()
    == df_final_pipeline.columns.tolist()
)

same_values = df_final.equals(df_final_pipeline)

print("Dataset boyutları aynı mı?:", same_shape)
print("Sütunlar ve sıraları aynı mı?:", same_columns)
print("Tüm değerler tamamen aynı mı?:", same_values)

"""### 7.4. Pipeline Çıktısının Kaydedilmesi

Doğrulanan pipeline çıktısı modelleme aşamasında kullanılmak üzere `data/processed` klasörüne kaydedilecektir.

Böylece temiz veri setinden başlayarak feature engineering ve final dataset oluşturma süreci tekrar çalıştırılabilir hale gelmiştir.
"""

import os

# Pipeline tarafından oluşturulan final dataset'in kayıt yolu

PIPELINE_OUTPUT_PATH = os.path.join(
    os.path.dirname(DATA_PATH),
    "credit_card_features.csv"
)

# Final pipeline çıktısını kaydediyoruz.

df_final_pipeline.to_csv(
    PIPELINE_OUTPUT_PATH,
    index=False
)

print("Dosya kaydedildi:")
print(PIPELINE_OUTPUT_PATH)

# Kaydedilen dosyanın doğru şekilde oluşturulduğunu kontrol ediyoruz.

check_pipeline_df = pd.read_csv(PIPELINE_OUTPUT_PATH)

print("Dosya mevcut mu?:", os.path.exists(PIPELINE_OUTPUT_PATH))
print("Kaydedilen dataset boyutu:", check_pipeline_df.shape)
print(
    "Beklenen boyutta mı?:",
    check_pipeline_df.shape == (30000, 51)
)

"""### Day 3 Result

Feature Engineering Pipeline başarıyla oluşturulmuş ve doğrulanmıştır. Pipeline, temiz veri setinden başlayarak 32 engineered feature üretmekte ve modelleme için 49 aday feature içeren final dataset'i otomatik olarak hazırlamaktadır. Pipeline çıktısının manuel olarak oluşturulan dataset ile aynı olduğu doğrulanmıştır.
"""



"""# Day 4 — Final Feature Validation

Bu bölümde modelleme aşamasında kullanılan feature seti yalnızca training data üzerinde incelenecektir.

Amaç:
- Engineered feature'ların target ile ilişkisini incelemek
- Yüksek korelasyonlu ve potansiyel olarak redundant feature'ları belirlemek
- Feature seçimi sırasında test setine bilgi sızmasını önlemek

Bu analiz feature'ları otomatik olarak silmek için değil, final feature setini doğrulamak için yapılmaktadır.
"""

from sklearn.model_selection import train_test_split

# Pipeline ile oluşturduğumuz final dataset'i kullanıyoruz.
# ID modele dahil edilmiyor.
# Target yalnızca y olarak kullanılıyor.

X = df_final_pipeline.drop(
    columns=[ID_COL, TARGET]
)

y = df_final_pipeline[TARGET]

# Burak'ın modelleme notebook'uyla aynı split ayarları
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("Train default oranı:", round(y_train.mean(), 4))
print("Test default oranı :", round(y_test.mean(), 4))

print("\nID X_train içinde mi?:", ID_COL in X_train.columns)
print("Target X_train içinde mi?:", TARGET in X_train.columns)

# Sadece final modelde gerçekten kullanılan engineered feature'ları seçiyoruz.

validation_features = [
    col for col in engineered_features
    if col in final_model_features_pipeline
]

print("Toplam engineered feature:", len(engineered_features))
print(
    "Final modelde kullanılan engineered feature:",
    len(validation_features)
)

print("\nValidation yapılacak feature'lar:")

for feature in validation_features:
    print("-", feature)

# ============================================================
# Engineered Feature - Target Relationship
# SADECE TRAIN SET
# ============================================================

X_val = X_train[validation_features].copy()

# Sonsuz değer varsa NaN'a çeviriyoruz.
X_val = X_val.replace([np.inf, -np.inf], np.nan)

# Korelasyon hesabı için eksik değerleri
# yalnızca TRAIN SET medyanı ile geçici olarak dolduruyoruz.
X_val = X_val.fillna(X_val.median())

train_validation = X_val.copy()
train_validation[TARGET] = y_train.loc[X_val.index]

target_corr = (
    train_validation
    .corr(numeric_only=True)[TARGET]
    .drop(TARGET)
    .sort_values(key=abs, ascending=False)
)

target_corr_df = pd.DataFrame({
    "feature": target_corr.index,
    "correlation_with_target": target_corr.values,
    "abs_correlation": target_corr.abs().values
})

print("Target ile en güçlü ilişkili engineered feature'lar:")

display(target_corr_df.head(15))

# ============================================================
# Engineered Feature - Feature Correlation
# ============================================================

corr_matrix = X_val.corr()

upper_triangle = corr_matrix.where(
    np.triu(
        np.ones(corr_matrix.shape),
        k=1
    ).astype(bool)
)

HIGH_CORR_THRESHOLD = 0.90

high_corr_pairs = []

for column in upper_triangle.columns:

    for index in upper_triangle.index:

        corr_value = upper_triangle.loc[index, column]

        if (
            pd.notna(corr_value)
            and abs(corr_value) >= HIGH_CORR_THRESHOLD
        ):

            high_corr_pairs.append({
                "feature_1": index,
                "feature_2": column,
                "correlation": corr_value
            })

high_corr_df = pd.DataFrame(high_corr_pairs)

if len(high_corr_df) == 0:

    print(
        "✅ |Correlation| >= 0.90 olan "
        "engineered feature çifti bulunamadı."
    )

else:

    high_corr_df["abs_correlation"] = (
        high_corr_df["correlation"].abs()
    )

    high_corr_df = high_corr_df.sort_values(
        "abs_correlation",
        ascending=False
    )

    print("Yüksek korelasyonlu engineered feature çiftleri:")

    display(high_corr_df)

print("=" * 60)
print("FINAL FEATURE VALIDATION")
print("=" * 60)

print("Train gözlem sayısı:", len(X_train))
print("Test gözlem sayısı :", len(X_test))

print(
    "Modeldeki toplam feature:",
    X_train.shape[1]
)

print(
    "Engineered feature:",
    len(validation_features)
)

print(
    "Yüksek korelasyonlu engineered feature çifti:",
    len(high_corr_df)
)

print("\nLeakage kontrolü:")
print("ID modelde:", ID_COL in X_train.columns)
print("Target modelde:", TARGET in X_train.columns)

print(
    "\n✅ Feature validation yalnızca training set üzerinde yapıldı."
)
print(
    "✅ Test set feature seçimi / korelasyon analizi için kullanılmadı."
)
print(
    "✅ Hiçbir feature otomatik olarak silinmedi."
)

print("YÜKSEK KORELASYONLU FEATURE ÇİFTLERİ")
print("=" * 70)

display(
    high_corr_df[
        ["feature_1", "feature_2", "correlation"]
    ].sort_values(
        "correlation",
        key=abs,
        ascending=False
    )
)

# Yüksek korelasyonlu feature'ların target ile ilişkisini karşılaştır

rows = []

for _, row in high_corr_df.iterrows():

    f1 = row["feature_1"]
    f2 = row["feature_2"]

    rows.append({
        "feature_1": f1,
        "feature_2": f2,
        "feature_corr": row["correlation"],
        "feature_1_target_corr": target_corr.get(f1, np.nan),
        "feature_2_target_corr": target_corr.get(f2, np.nan)
    })

comparison_df = pd.DataFrame(rows)

display(comparison_df)

"""### Feature Doğrulama Sonucu
En güçlü tekrar eden bilgi `avg_bill_amt` ile `avg_positive_bill_amt` arasında görülmüştür (r ≈ 1.00). Bu iki değişken neredeyse aynı bilgiyi taşımakta ve target ile ilişkileri de oldukça benzerdir. Bu nedenle `avg_positive_bill_amt` model sadeleştirmesi için çıkarılma adayı olarak belirlenmiş ve modelleme aşamasında veri setinden çıkarılmıştır.

Diğer yüksek korelasyonlu feature’lar ise farklı zaman dönemlerine ait davranışsal bilgiler taşıdıkları için korunmuştur. ID ve target değişkenlerinin model girdileri içerisinde bulunmadığı doğrulanmış, feature değerlendirmesi yalnızca training set üzerinde gerçekleştirilerek test setinden bilgi sızması önlenmiştir.




"""

